### ISSUE TITLE
尝试升级10.14.2屏幕背光不能用

### ISSUE THREAD

**Issue by CyJaySong** [xxxzc/xps15-9550-macos#10]
我使用的wmchris的,升级10.14.2后屏幕背光不能用了.

**Comment by xxxzc** [comment]
wmchris 的那个 patch 没必要了，建议使用最新的 [acidanthera/WhateverGreen](https://github.com/acidanthera/WhateverGreen) 加上 [RehabMan/applebacklightfixup](https://bitbucket.org/RehabMan/applebacklightfixup/downloads/) 里的 SSDT-PNLF.aml
