### ISSUE TITLE
无法进入系统，提示Couldn't allocate runtime area

### ISSUE THREAD

**Issue by journey-ad** [xxxzc/xps15-9550-macos#11]
安装时能够正常安装，安装完成手动重启后无法进入系统
提示Couldn't allocate runtime area，稍后点击回车后会进入戴尔支持助手的内存测试页面，测试结果无异常，求解

**Comment by xxxzc** [comment]
Clover GUI 下按 F11 删除下 nvram

**Comment by journey-ad** [comment]
使用[这个 issues](https://github.com/darkhandz/XPS-9550-Mojave/issues/11) 中提到的方法，删除所有第三方主题、替换 `AptioMemoryFix-64.efi` 为 `OsxAptioFix2Drv-free2000.efi` 后状况有所缓解，我会再进行尝试

`OsxAptioFix2Drv-free2000.efi` 下载地址及原因分析
https://www.nickwoodhams.com/x99-hackintosh-osxaptiofixdrv-allocaterelocblock-error-update/

**Comment by xxxzc** [comment]
按 F11 reset nvram 没有用么？更新后我也遇到了这个问题，但是 reset nvram 后就解决了，

**Comment by journey-ad** [comment]
当时按 F11 后只是重启了，似乎是没有效果
现在睡眠后唤醒会出现闪屏/花屏，爬到一篇帖子，介绍了修复方法，但是我对这里面的技术细节不是很了解，你看看有无帮助？
http://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1767983

append:
此方法测试似乎有效，闪屏/花屏状况依然有，但频率低了很多，几乎可以忽略

**Comment by xxxzc** [comment]
> 当时按 F11 后只是重启了，似乎是没有效果
> 现在睡眠后唤醒会出现闪屏/花屏，爬到一篇帖子，介绍了修复方法，但是我对这里面的技术细节不是很了解，你看看有无帮助？
> http://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1767983
> 
> append:
> 此方法测试似乎有效，闪屏/花屏状况依然有，但频率低了很多，几乎可以忽略

我的睡眠唤醒一直都很正常= =，你是 4k 屏还是 1080p，CPU是 i5 还是 i7 ，有外接显示器吗？
有没有用 Clover Configurator 在 SMBIOS 栏里选择 MacBookPro13,3 Model，生成后应该是这样：

```
	<key>SMBIOS</key>
	<dict>
		<key>BiosReleaseDate</key>
		<string>10/30/2018</string>
		<key>BiosVendor</key>
		<string>Apple Inc.</string>
		<key>BiosVersion</key>
		<string>MBP133.88Z.F000.B00.1810301606</string>
		<key>Board-ID</key>
		<string>Mac-A5C67F76ED83108C</string>
		<key>BoardManufacturer</key>
		<string>Apple Inc.</string>
		<key>BoardSerialNumber</key>
		<string>?</string>
		<key>BoardType</key>
		<integer>10</integer>
		<key>BoardVersion</key>
		<string>1.0</string>
		<key>ChassisAssetTag</key>
		<string>MacBook-Aluminum</string>
		<key>ChassisManufacturer</key>
		<string>Apple Inc.</string>
		<key>ChassisType</key>
		<string>0x09</string>
		<key>EfiVersion</key>
		<string>251.0.0.0.0</string>
		<key>Family</key>
		<string>MacBook Pro</string>
		<key>FirmwareFeatures</key>
		<string>0xFC0FE13F</string>
		<key>FirmwareFeaturesMask</key>
		<string>0xFF1FFF3F</string>
		<key>LocationInChassis</key>
		<string>Part Component</string>
		<key>Manufacturer</key>
		<string>Apple Inc.</string>
		<key>Mobile</key>
		<true/>
		<key>PlatformFeature</key>
		<string>0x1A</string>
		<key>ProductName</key>
		<string>MacBookPro13,3</string>
		<key>SerialNumber</key>
		<string>?</string>
		<key>SmUUID</key>
		<string>?</string>
		<key>Trust</key>
		<true/>
		<key>Version</key>
		<string>1.0</string>
	</dict>
	<key>SystemParameters</key>
	<dict>
		<key>CustomUUID</key>
		<string>?</string>
		<key>InjectKexts</key>
		<string>Detect</string>
		<key>InjectSystemID</key>
		<true/>
	</dict>
```

**Comment by journey-ad** [comment]
经过两天的观察与体验，目前已基本没问题，应用的更改有：
- 更换内存修复 EFI 驱动（重要）
- 更换 Clover 配置
- 添加显示器描述文件至系统 Overrides 目录
- 填写正确的 SMBIOS 配置信息

我的CPU为I7 屏幕分辨率为4K
希望能为后来者提供帮助

**Comment by xxxzc** [comment]
可以告知一下更换了哪些 Clover 配置么？
EDID 可能确实是特定屏幕型号会有的问题，jardenliu 的 Clover 配置里也有注入 EDID
有空我会试一下花屏是否是 SMBIOS 不完整（board-id 未指定）引起的
Edited:
emm...好像 SMBIOS 填过一次后系统就记住了，测试不了

**Comment by xxxzc** [comment]
今天我也遇到了一次唤醒后花屏，按下电源键恢复了。
看了下 Console，有个 log 显示读取 egpu 的配置失败，有点怀疑是因为没有 disable-external-gpu，有待多观察

**Comment by xxxzc** [comment]
emm。。。现在才知道静电也会导致显示器花屏，我感觉我这种非常非常偶尔出现的花屏很有可能是静电的缘故，因为按下电源键就恢复。
