### ISSUE TITLE
似乎5G速度有问题

### ISSUE THREAD

**Issue by CyJaySong** [xxxzc/xps15-9550-macos#12]
测试了一下，只能拉到30mb/s。

**Comment by CyJaySong** [comment]
解决了，在EFI / CLOVER / kexts / Other中放置以下kext：
FakePCIID.kext
FakePCIID_Broadcom_WiFi.kext
AirportBrcmFixup.kext（使用这个，需要Lilu.kext）
custom flag 添加 brcmfx-country=#a  可能还需要加   -lilubetaall

**Comment by xxxzc** [comment]
我这边网络环境没那么好= =
能否帮忙测试一下不加 FakePCIID.kext 和 FakePCIID_Broadcom_WiFi.kext，只加 brcmfx-country=#a 时的情况？

**Comment by CyJaySong** [comment]
试了一下，这样没有效果

**Comment by CyJaySong** [comment]
但是有个问题，由于加了 -lilubetaall，  不够稳定。有时候经常不能开机。哎，，，

**Comment by xxxzc** [comment]
@CyJaySong 那可能是 fake device id 起作用（是 airportbrcmfixup 建议的）。我研究下如何直接在 config.plist 加，不用 fakepciid。
网络变化是会容易导致进不了系统。-lilubetaall 应该没问题吧，之前也都有这个参数。

**Comment by xxxzc** [comment]
查了一些资料，个人认为应该不是 FakePCIID.kext 和 FakePCIID_Broadcom_WiFi.kext 的问题，-lilubetaall 参数也没有必要。
之前 1.1.8 的 airportbrcmfixup 把 DW1830 识别成了第三方的 WiFi 卡，频段不全。[AirportBrcmFixup/releases](https://github.com/acidanthera/AirportBrcmFixup/releases) 1.1.9 修复了这个问题，现在是识别为 `AirPort Extreme`，可以试一试。
另外不正确的 `brcmfx-country` 确实会影响 5g 的速度。

**Comment by CyJaySong** [comment]
airportbrcmfixup 升级为 1.1.9 后，brcmfx-country=#a  速度上来了。未使用FakePCIID.kext 和 FakePCIID_Broadcom_WiFi.kext以及-lilubetaall
