### ISSUE TITLE
插入耳机没反应

### ISSUE THREAD

**Issue by CyJaySong** [xxxzc/xps15-9550-macos#13]
插入耳机后，没声音，没设备，然后扬声器也没的声音了，插掉耳机后也是

 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by xxxzc** [comment]
装了 ALC298PluginFix 吗？或者重启一下。

**Comment by CyJaySong** [comment]
@xxxzc 装了的


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by CyJaySong** [comment]
声卡id注入28修复完成。
