### ISSUE TITLE
睡眠修复没用

### ISSUE THREAD

**Issue by CyJaySong** [xxxzc/xps15-9550-macos#14]
按照README.md 尝试修复睡眠，没效果

**Comment by xxxzc** [comment]
不能睡眠还是唤醒失败？没遇到此问题。

**Comment by CyJaySong** [comment]
@xxxzc 唤醒成了开机。。。


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by CyJaySong** [comment]
我们QQ谈吧，方便快捷，解决后commit上来，2538053693

**Comment by CyJaySong** [comment]
使用 [wmchris](https://github.com/wmchris/DellXPS15-9550-OSX) 的 SSDT-UPRW.aml 和 SSDT-PTSWAK.aml 和他 config.plist 中的所有
 <key>DSDT</key>
		<dict>
			<key>Patches</key>

然后删掉关于 hdef 的
