### ISSUE TITLE
Dock type c does not work completely

### ISSUE THREAD

**Issue by retomi** [xxxzc/xps15-9550-macos#16]
Hi, unfortunately the dock connected to the type c doesn't work the Ethernet and the USB. The only thing that works is HDMI. For now I had to go back to the wmchris repo. Thank you for your support and your availability.

**Comment by xxxzc** [comment]
Is dock using Thunderbolt? I can't test it since I only have a type-c to dp connector...
You can try replace SSDT-THBT with SSDT-TYPC and SSDT-YTBT, and add following code to config.plist-ACPI-DSDT-Patches:

```
				<dict>
					<key>Comment</key>
					<string>rename _RMV to XRMV, pair with SSDT-TYPC.aml</string>
					<key>Disabled</key>
					<false/>
					<key>Find</key>
					<data>X1JNVg==</data>
					<key>Replace</key>
					<data>WFJNVg==</data>
				</dict>
```

**Comment by retomi** [comment]
Yes, my dock uses Thunderbolt. It works. I deleted SSDT-THBT.aml and added SSDT-TYPC.aml and SSDT-YTBT.aml. In the config.plist ACPI-DSDT-Patches I added
<dict>
					

				<dict>
					<key>Comment</key>
					<string>rename _RMV to XRMV, pair with SSDT-TYPC.aml</string>
					<key>Disabled</key>
					<false/>
					<key>Find</key>
					<data>X1JNVg==</data>
					<key>Replace</key>
					<data>WFJNVg==</data>
				</dict>
				<dict>
					<key>Comment</key>
					<string>Rename XTBT to YTBT, pair with SSDT-YTBT.aml</string>
					<key>Disabled</key>
					<false/>
					<key>Find</key>
					<data>pABYVEJUVEJTRUNQR04=</data>
					<key>Replace</key>
					<data>pABZVEJUVEJTRUNQR04=</data>
				</dict>

Thank you for your support and for your work.
