### ISSUE TITLE
音频设备时有时无

### ISSUE THREAD

**Issue by jackhanyuan** [xxxzc/xps15-9550-macos#17]
有时候开机，声音无法播放，查看 系统偏好设置-声音-输入输出设备 均未显示。
重建缓存  sudo kextcache -i  ，然后重启，问题解决（而且外放、耳机都表现完美）。但是下次开机有很大概率又出现这种情况。
我的声卡是ALC298，参考(https://github.com/jardenliu/XPS15-9560-Mojave) 方法，注入 ID：72，貌似没多大变化。

机型配置：xps9550 4k美版 16g内存 海力士1T固态  声卡:ALC298

**Comment by xxxzc** [comment]
确实有这个问题，之前搜过不少相关信息，也尝试过不少修改，没找到解决方法。

不是 ID 的问题。使用 30 只是因为它可以在不使用 pluginfix 和 codecommander 下正常驱动耳机，之前使用 72 + pluginfix 依然会出现偶尔开机丢失音频的情况，甚至更严重。

不知道其他 Repo 是否能保证开机不丢失音频，可以帮忙测试一下。。。

**Comment by jackhanyuan** [comment]
@xxxzc 今天在终端下用命令 kextstat 看了驱动加载情况，发现是 AppleHDAHardwareConfigDriver 和 AppleHDA" are not loaded 没有加载导致上述问题，搜索了一下，找到一种解决方案 [AppleHDA kext not load](https://www.insanelymac.com/forum/topic/299901-applehda-kext-not-load/) 貌似对我是有效的。
问题可能由于DSDT中IRQ冲突造成的，解决方法是打开config.plist，在 Acpi - Fixes 中勾选 FixHPET，修改后，开关机几次，暂时音频正常。

**Comment by jackhanyuan** [comment]
多次测试后，问题又复现了，这真是个迷之问题……
但确实是 AppleHDAHardwareConfigDriver 和 AppleHDA 没有加载导致的。

**Comment by xxxzc** [comment]
IRQ那个我也试过，没有用。

AppleHDAHardwareConfigDriver 和 AppleHDA 没有加载，可以把 AppleHDA 驱动加入到
KernelAndKextPatches -> ForceKextsToLoad 试一试

```
		<key>ForceKextsToLoad</key>
		<array>
			<string>\System\Library\Extensions\AppleHDA.kext</string>
		</array>
```

**Comment by CyJaySong** [comment]
我没改其他什么东西，放了 CodecCommander.kext 之后就没遇到过开机丢失音频的问题了

**Comment by jackhanyuan** [comment]
@CyJaySong 我试着加了CodecCommander.kext ，也不可以。

**Comment by CyJaySong** [comment]
@jackhanyuan  你是不是改过什么东西


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by CyJaySong** [comment]
@jackhanyuan  我对这个不是很了解，所以我基本保持和xxxcz一致的。除了适应自己电脑的内存修正


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by jackhanyuan** [comment]
> @jackhanyuan 你是不是改过什么东西
> 
> :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

我的硬盘是海力士，只加了硬盘补丁，其它也是一致的。

**Comment by jackhanyuan** [comment]
> IRQ那个我也试过，没有用。
> 
> AppleHDAHardwareConfigDriver 和 AppleHDA 没有加载，可以把 AppleHDA 驱动加入到
> KernelAndKextPatches -> ForceKextsToLoad 试一试
> 
> ```
> 		<key>ForceKextsToLoad</key>
> 		<array>
> 			<string>\System\Library\Extensions\AppleHDA.kext</string>
> 		</array>
> ```

@xxxzc 这个测试了一周，问题还是会复现。

**Comment by xxxzc** [comment]
[AppleALC 1.3.8](https://github.com/acidanthera/AppleALC/releases/tag/1.3.8) 提到 `Fixed rare random audio init failure on 10.14` 可能解决的就是这个问题。@jackhanyuan 
需要多测试

**Comment by jackhanyuan** [comment]
@xxxzc 好的，我试一段时间。
