### ISSUE TITLE
看9560 jardenliu可以黑果雷电3表示羡慕，希望大神加把劲

### ISSUE THREAD

**Issue by zjq860328** [xxxzc/xps15-9550-macos#19]

**Comment by xxxzc** [comment]
雷电三是可以的，但是不包括外置显卡，请参考 Issue #16。
外置显卡的支持很不好，无法热插拔，且比较频繁地开机没驱动（我的 gaming box rx580 经常性地开机没驱动成功）。我没时间去研究怎么解决，可以关注下 [lenovo-t480s-tb3-egpu-amd-rx580-detection](https://www.tonymacx86.com/threads/lenovo-t480s-tb3-egpu-amd-rx580-detection.272391/#post-1915926) 和 [in-progress-ssdt-for-thunderbolt-3-hotplug](https://www.tonymacx86.com/threads/in-progress-ssdt-for-thunderbolt-3-hotplug.248784/) 的进展。

**Comment by zjq860328** [comment]
谢谢，我还是专门把技嘉1080的盒子卖了换的akitio+RX580结果还是识别不了，看来9550是时候该退役了

**Comment by CyJaySong** [comment]
我现在Type-C那个接口不能热插拔了，只能开机前就插上，设备才能使用....不知道是不是xxxzc故意这样弄的

**Comment by xxxzc** [comment]
> 我现在Type-C那个接口不能热插拔了，只能开机前就插上，设备才能使用....不知道是不是xxxzc故意这样弄的

肯定不是呀，我的 typec 设备都正常使用的

**Comment by CyJaySong** [comment]
晚上回去我 QQ上来骚扰你。嘿嘿

**Comment by jackhanyuan** [comment]
> > 我现在Type-C那个接口不能热插拔了，只能开机前就插上，设备才能使用....不知道是不是xxxzc故意这样弄的
> 
> 肯定不是呀，我的 typec 设备都正常使用的

我试了下我的Type C也是不可以热拔插，开机前插上没问题。

**Comment by CyJaySong** [comment]
@jackhanyuan  这位仁兄也这样@xxxzc


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by xxxzc** [comment]
麻烦帮忙试下 Issue #16 的方法有没有这个问题。@CyJaySong @jackhanyuan

**Comment by CyJaySong** [comment]
> 麻烦帮忙试下 Issue #16 的方法有没有这个问题。@CyJaySong @jackhanyuan

 Issue #16 的方法没问题，可以热插拔

**Comment by jackhanyuan** [comment]
> 麻烦帮忙试下 Issue #16 的方法有没有这个问题。@CyJaySong @jackhanyuan
@xxxzc 按照Issue #16 方法，type c 接口可以热拔插了（并且开机前不插，开机后插上也是可以用的）。

**Comment by xxxzc** [comment]
把配置换成那个了，感谢测试。

**Comment by xxxzc** [comment]
放弃雷电吧
