### ISSUE TITLE
6.1版本风扇声音很大

### ISSUE THREAD

**Issue by jackhanyuan** [xxxzc/xps15-9550-macos#20]
6.1版本风扇声音很大，发热感觉也会比之前的大一些，5.4及之前版本没问题。

**Comment by xxxzc** [comment]
你的 CPU 是 i7 吗？可以用 intel-power-gadget 观察下频率和功耗变化。我 i5 日常使用温度挺正常。（看在线视频的时候发热确实大）

另外麻烦查看下 System Report - Graphics 里是否只有核显存在，以及型号是否正确。

**Comment by jackhanyuan** [comment]
CPU:i7-6700HQ
10.14.5开始，我的固态补丁也不用打了，所以config用的和你的是一模一样，完全没有改，系统报告里只有530显卡。

正常使用时cpu 功耗5W 温度在39-41度左右，看网页高清视频cpu 功耗10W左右 温度在50度左右，感觉整体功耗和温度和之前差不多，但开机几分钟风扇就开始声音很大了，电脑C面温度比之前要热一些。

**Comment by xxxzc** [comment]
我发现很有可能是我把 `SSDT-DDGPU` 删了导致的。我以为 `disable-external-gpu` 已经可以屏蔽独立显卡了，因为系统报告了只有核显，以前如果没有屏蔽会显示两张显卡。
但实测发现保留这个补丁，power-gadget 显示的待机功耗是 2.3 W 左右，删了后是 5 W 左右。

**Comment by jackhanyuan** [comment]
可以了，用了你最新的clover，升级了10.15 beta3，功耗降下来了，风扇也正常，不错。

**Comment by xxxzc** [comment]
beta3 你有没有遇到开机弹 icloud 登录出错的问题

**Comment by jackhanyuan** [comment]
没有遇到，iCloud正常，但是解锁的时候和关机的时候会卡顿一下，其他暂时没发现问题。
