### ISSUE TITLE
６.１版本　唤醒的时候会花屏　其他完美

### ISSUE THREAD

**Issue by wschijin** [xxxzc/xps15-9550-macos#21]
６.１版本　唤醒的时候会花屏　其他完美

**Comment by xxxzc** [comment]
没遇到这个问题。。是每次都会吗？花屏是瞬间还是就直接无法用了？

**Comment by wschijin** [comment]
已经解决了 我是FHD屏幕 WhateverGreen.kext 1.29 1.28 会花屏 
使用1.27版本能解决..
谢谢大大

**Comment by xxxzc** [comment]
看你的描述，我感觉有可能是 1.2.8 新加入的 `enable-dpcd-max-link-rate-fix` 导致的，可以把  config.plist 里的这一项删了，用最新的 whatevergreen 再试试。
