### ISSUE TITLE
Trackpad does not work after standby

### ISSUE THREAD

**Issue by retomi** [xxxzc/xps15-9550-macos#22]
Hi, often after the standby the trackpad doesn't work anymore. Is there any way to solve it? Thanks so much for your support

**Comment by xxxzc** [comment]
Sorry, I have never encountered this problem.
After running [these scripts](https://github.com/xxxzc/xps15-9550-macos#disable-hibernation-and-fix-sleep-issues) and unchecking all the checkbox in the `Energy Saver` panel, sleep works like a charm, even after a every long time.

**Comment by retomi** [comment]
thanks for the support.
