### ISSUE TITLE
Sometimes audio doesn't work

### ISSUE THREAD

**Issue by retomi** [xxxzc/xps15-9550-macos#23]
Sometimes audio doesn't work, despite the sudo kextcache -u / and reboots.

I tried to add these copies from the wmchris repo:

- FakePCIID_Intel_HDMI_Audio.kext
- FakePCIID.kext

and I deleted this from the config.plist
<Key> Audio </ key>
<Dict>
<Key> Inject </ key>
<Integer> 30 </ integer>
<Key> ResetHDA </ key>
<True />
</ Dict>
sudo touch / System / Library / Extensions && sudo kextcache -u /
On reboot it works normally, even if the audio on the HDMI does not seem to be recognized, but the rest seems to work properly.

**Comment by xxxzc** [comment]
In my situation, I need those config to prevent audio to be lost after wake when using battery.  I will do more test to find a better solution.

Updated:
I use layout-id 30 with modified CodecCommander now and removed all other audio items in config.plist. It seems to be fine.

Anyway, you have your own solution.
