### ISSUE TITLE
Could  you give 6700hq's CLOVER?

### ISSUE THREAD

**Issue by Skilling-Kiss** [xxxzc/xps15-9550-macos#24]
my driver is differert from cpu,but i can't fix it,plz help me,ths!

**Comment by xxxzc** [comment]
Do you encounter any problems? 6300hq and 6700hq are using the same model, theoretically, my config should work.

If not, you can:
- Replace `CPUFriendDataProvider.kext` with [this one](https://github.com/wmchris/DellXPS15-9550-OSX/tree/10.15/10.15/CLOVER/kexts/Other/CPUFriendDataProvider.kext)
- Or use [one-key-cpufriend](https://github.com/stevezhengshiqi/one-key-cpufriend) to generate a new one

**Comment by Skilling-Kiss** [comment]
NO,i just thought 6700 may have different issues,for example,CPU boost may have some trouble,i'll try later,ths for reply.
