### ISSUE TITLE
Can not boot

### ISSUE THREAD

**Issue by tiger511** [xxxzc/xps15-9550-macos#25]
It doesnt even boot with your latest clover.It stuck in boot screen.Please recheck your CLOVER folder.

**Comment by xxxzc** [comment]
It's my daily driver.

Please use `-v` boot arg to see which step were you stuck.

**Comment by tiger511** [comment]
sorry my bad.Everything works fine.I must have mixed clover versions and kexts.But it requires a lot of restart and KP before installation.After kextcache,everything running smooth so far.But i have one problem with kernel_task.I'll open seperate issue.You can close this one.

**Comment by xxxzc** [comment]
Installation required many times of reboot, it's normal.
