### ISSUE TITLE
kernel_task high cpu usage when connect to AC

### ISSUE THREAD

**Issue by tiger511** [xxxzc/xps15-9550-macos#26]
This is not related to AppleALC.This only happens when im connected to power.kernel_task stays between 40-60% CPU usage on idle.
To get rid of it, i have to unplug laptop,sleep and then wake.Then kernel_task stays around 5-10%. As soon as i plug it back again,it goes to 50% cpu usage again.

It happened in mojave for me too.

CPU: i3-6100h
GPU: Intel HD 530 only
SSD: 512GB Samsung pm951 in APFS file system
<img width="745" alt="Screen Shot 2019-08-28 at 5 45 31 PM" src="https://user-images.githubusercontent.com/53279423/63853250-0667a080-c9bc-11e9-9a85-9df6094485a6.png">
.

**Comment by xxxzc** [comment]
Please give me:
1. your clover folder
2. origin DSDT file (press F4 or Fn+F4 on Clover GUI)

With config that I pushed today, kernel_task stays under 4% on idle on my i5 laptop.

**Comment by tiger511** [comment]
I will try your config right now.Which one is better OC or Clover?

**Comment by xxxzc** [comment]
Clover is more stable currently.

Do a NVRAM reset before using new config.

**Comment by tiger511** [comment]
I've tried new Settings with few changes ,still same.kernel_task jumps to 20-30% and cpu usage stuck at 2.6GHz (My cpu is i3-6100h 2.7ghz no turbo boost) .I've attached the video below:
https://youtu.be/40oEYdreJTA

Look at 00:18 as soon as i plug in adapter ,kernel_task spikes and stays there.Then i unplugged it at 00:41 ,still high cpu until i sleep and wake laptop .After sleep/wake on battery it returns to normal cpu usage with cpu around 1GHz.

Attached Clover with original DSDT
[CLOVER.zip](https://github.com/xxxzc/xps15-9550-macos/files/3552549/CLOVER.zip)

**Comment by tiger511** [comment]
I suspect its a hardware issue probably bad motherboard. 🤔

**Comment by xxxzc** [comment]
Hmm, I am not an expert in debugging.
Please unplug and replug the adapter, and give me the `pmset -g log` result in text.

**Comment by tiger511** [comment]
[pmsetlog.txt](https://github.com/xxxzc/xps15-9550-macos/files/3561477/pmsetlog.txt)

**Comment by regae** [comment]
make sure TPD0 is not loaded by VoodooI2C,
remove 8086,a160 from info.plist VoodooI2C
or use disable-i2c0 ssdt _STA

for me, my touchpad is I2C1, TPD1
if TPD0 is loaded by VoodooI2C, when its plugged in (AC), my cpu never down below 2.9GHZ,
always 2.9 - 3.4Ghz

**Comment by tiger511** [comment]
With latest clover config from this rep, I only see TPXX in ioregistryexplorer.
<img width="744" alt="Screen Shot 2019-11-06 at 6 17 59 AM" src="https://user-images.githubusercontent.com/53279423/68294090-4ce11780-005d-11ea-943f-2e87d371dd07.png">

**Comment by tiger511** [comment]
> make sure TPD0 is not loaded by VoodooI2C,
> remove 8086,a160 from info.plist VoodooI2C
> or use disable-i2c0 ssdt _STA
> 
> for me, my touchpad is I2C1, TPD1
> if TPD0 is loaded by VoodooI2C, when its plugged in (AC), my cpu never down below 2.9GHZ,
> always 2.9 - 3.4Ghz

This fixed my issue as well.Thanks man.

**Comment by xxxzc** [comment]
I update my SSDT-TPXX to disable I2C0 [SSDT-TPDX.zip](https://github.com/xxxzc/xps15-9550-macos/files/3817073/SSDT-TPDX.zip), can you help me test it? @tiger511  @regae 

To use this SSDT, you need:
1. remove all I2C related SSDT and patches such as SSDT-TPXX, SSDT-I2C, _CRS and _STA renaming
2. restore VoodooI2C to default
3. disable [Rename GPI0._STA to XSTA](https://github.com/xxxzc/xps15-9550-macos/blob/4d8630d67298540e327180d283d13412ad7aecaf/CLOVER/config.plist#L73) patch

**Comment by regae** [comment]
i see you set GPEN to one in order to enable GPIO,
why not just just set SDM1 to zero for CRS method if you want to use SBFG?

**Comment by xxxzc** [comment]
> i see you set GPEN to one in order to enable GPIO,
> why not just just set SDM1 to zero for CRS method if you want to use SBFG?

Setting SDM1 to zero requires  _OSI patch(_OSI renaming should be avoid according to OpenCore documentation and setting OSYS directly doesn't work ) and GPI0 still need to be activated(GPI0._STA patch or `GPEN != Zero`).

In this way, no other patch is needed and currently I can't find side effect on this assignment.

**Comment by regae** [comment]
what about change the default OSYS in _INI method before if statement?
0BD0074F 535953 to 0BDF074F 535953

**Comment by xxxzc** [comment]
> what about change the default OSYS in _INI method before if statement?
> 0BD0074F 535953 to 0BDF074F 535953

Great idea, thanks

**Comment by regae** [comment]
and for OSID method, replace WN81 (or whatever you want to use) to OSXX, and in ssdt create Name (OSXX, "Darwin"), so we dont need to set ACOS to get brightness key working

you can put if statement _OSI "Darwin" 
Name (OSXX, "Windows 2013")
If (_OSI ("Darwin"))
{ Name (OSXX, "Darwin") }

or Return to default one with External StrObj

i have no idea though which one is best, XOSI method or my method

**Comment by xxxzc** [comment]
Why not just set ACOS and GPEN, can you give me a reason? Everything works just fine for me, without any _OSI related patch...

**Comment by regae** [comment]
like you said before, setting OSYS directly doesn't work
just afraid it has something to do with the early calls of method (need analyzed),

what about the idea before? is it working for you?

**Comment by tiger511** [comment]
> I update my SSDT-TPXX to disable I2C0 [SSDT-TPDX.zip](https://github.com/xxxzc/xps15-9550-macos/files/3817073/SSDT-TPDX.zip), can you help me test it? @tiger511 @regae
> 
> To use this SSDT, you need:
> 
> 1. remove all I2C related SSDT and patches such as SSDT-TPXX, SSDT-I2C, _CRS and _STA renaming
> 2. restore VoodooI2C to default
> 3. disable [Rename GPI0._STA to XSTA](https://github.com/xxxzc/xps15-9550-macos/blob/4d8630d67298540e327180d283d13412ad7aecaf/CLOVER/config.plist#L73) patch

I just tested it and it works as expected.
