### ISSUE TITLE
可以直接升级catalina吗

### ISSUE THREAD

**Issue by jioswu** [xxxzc/xps15-9550-macos#28]
10.14.6可以直接升级到catalina吗

**Comment by xxxzc** [comment]
我是从 14.6 升 beta 然后升了好几次 beta 都没遇到问题，最好还是备份下吧。

**Comment by nick2834** [comment]
相同的配置 卡进度条

**Comment by xxxzc** [comment]
加上 `-keepsysms -v`  看看是卡哪里了

**Comment by nick2834** [comment]
> 加上 `-keepsysms -v` 看看是卡哪里了

我用的是OC版本的  卡NVME

**Comment by xxxzc** [comment]
用 Clover 升试试吧，OC 问题挺多

卡 NVME 显示的信息是啥？

**Comment by nick2834** [comment]
> 用 Clover 升试试吧，OC 问题挺多
> 
> 卡 NVME 显示的信息是啥？
OC 最近更新频繁，比Clover性能上更强一些。
 我更换了硬盘，原来的硬盘不支持NVME，估计是这个原因
