### ISSUE TITLE
睡眠后屏幕会闪，不知道大佬你有没有这种情况？

### ISSUE THREAD

**Issue by xyx208** [xxxzc/xps15-9550-macos#3]
如题！我的是4k屏。

**Comment by xxxzc** [comment]
会闪是什么情况= =一直闪？

**Comment by xyx208** [comment]
> 会闪是什么情况= =一直闪？

就是闪一下，然后好一会又闪。。。。随机的感觉，但是睡眠后就会有。
另外，锁屏黑屏后，点不亮屏幕。。。。。电源按键是亮的，键盘不亮，屏幕黑着。。。。

**Comment by xxxzc** [comment]
> > 会闪是什么情况= =一直闪？
> 
> 就是闪一下，然后好一会又闪。。。。随机的感觉，但是睡眠后就会有。
> 另外，锁屏黑屏后，点不亮屏幕。。。。。电源按键是亮的，键盘不亮，屏幕黑着。。。。

4k 可以先试试加 -cdfon 启动参数。另外现在用的 framebuffer patch 是 jardenliu 9560 的，所以可能会有问题，正在修改。参考 https://www.tonymacx86.com/threads/guide-intel-framebuffer-patching-using-whatevergreen.256490/

睡眠问题还在看，看了下 log 是因为 com.apple.iokit.IOUSBHostFamily。现在正在尝试 https://www.tonymacx86.com/threads/release-intel-fb-patcher-v1-4-3.254559/ 这个方法。

**Comment by xyx208** [comment]
> https://www.tonymacx86.com/threads/guide-intel-framebuffer-patching-using-whatevergreen.256490/

大佬，等你的好消息！

**Comment by xxxzc** [comment]
现在应该正常了。瞎忙了一天才发现睡眠唤醒是因为我之前瞎删 SSDT 导致的。。。我以为 Whatevergreen 的 disable-external-gpu 是指独立显卡，所以把禁用独立显卡的 ssdt 删了。现在才发现原来是指外接显卡。。。

**Comment by xyx208** [comment]
我试试，感谢！

**Comment by xyx208** [comment]
> 现在应该正常了。瞎忙了一天才发现睡眠唤醒是因为我之前瞎删 SSDT 导致的。。。我以为 Whatevergreen 的 disable-external-gpu 是指独立显卡，所以把禁用独立显卡的 ssdt 删了。现在才发现原来是指外接显卡。。。

我今天试了一下，还是一样会黑屏，感觉系统是唤醒了，但是，就是不显示，屏幕背光可以看到是有的。

**Comment by xxxzc** [comment]
> > 现在应该正常了。瞎忙了一天才发现睡眠唤醒是因为我之前瞎删 SSDT 导致的。。。我以为 Whatevergreen 的 disable-external-gpu 是指独立显卡，所以把禁用独立显卡的 ssdt 删了。现在才发现原来是指外接显卡。。。
> 
> 我今天试了一下，还是一样会黑屏，感觉系统是唤醒了，但是，就是不显示，屏幕背光可以看到是有的。

看看 `系统报告` 中 `图形卡/显示器` 的信息中是不是只有核显

**Comment by xyx208** [comment]
> > > 现在应该正常了。瞎忙了一天才发现睡眠唤醒是因为我之前瞎删 SSDT 导致的。。。我以为 Whatevergreen 的 disable-external-gpu 是指独立显卡，所以把禁用独立显卡的 ssdt 删了。现在才发现原来是指外接显卡。。。
> > 
> > 
> > 我今天试了一下，还是一样会黑屏，感觉系统是唤醒了，但是，就是不显示，屏幕背光可以看到是有的。
> 
> 看看 `系统报告` 中 `图形卡/显示器` 的信息中是不是只有核显

我换回了我在10.13.6的配置，已经正常了，感谢！

**Comment by xxxzc** [comment]
我换回 4k 屏修复了下问题，现在应该一切正常了。
如果有时间麻烦帮忙测试一下看看哪里还有问题，谢啦~

**Comment by upupming** [comment]
> 我换回了我在10.13.6的配置，已经正常了，感谢！

请问是如何修复睡眠唤醒黑屏的问题的呢？
