### ISSUE TITLE
hd530带的动4K屏吗？为啥我的感觉掉帧严重

### ISSUE THREAD

**Issue by SeanPcWoo** [xxxzc/xps15-9550-macos#30]
大佬，我现在是14.5，跟你一样的配置 9550，16G双通道内存，然后是 4K 屏，感觉即使双通道内存，在使用的时候还是会有掉帧的情况。更别提哔哩哔哩后者斗鱼看直播了，弹幕一开，直接卡的出奇。请问大佬，你的 efi 有解决这个问题吗？现在 cotilina 正式版的可以使用你的这个吗？

**Comment by xxxzc** [comment]
看在线视频确实卡，10.15 使用正常
