### ISSUE TITLE
"Caps Lock" button problem

### ISSUE THREAD

**Issue by tiger511** [xxxzc/xps15-9550-macos#32]
WIth latest release, the caps lock button's light does not turn on when its activated.

**Comment by xxxzc** [comment]
Are you using mojave? Latest release of [VoodooPS2](https://github.com/acidanthera/VoodooPS2/releases/latest) has a workaround for Mojave, maybe works.

Btw, dose high cpu usage fixed and dose regae's solution work?

**Comment by tiger511** [comment]
Im using Latest version of Catalina, 10.15.1
About those high cpu usage, i didnt find any solution. There are more people having this issues now 

> @xxxzc: I delete the link since they are not relevant topics 

I'll try his solution now,and let you know.
