### ISSUE TITLE
WindowServer High cpu usage

### ISSUE THREAD

**Issue by tiger511** [xxxzc/xps15-9550-macos#33]
WindowServer system process always use 15-40% CPU usage even when only using chrome or any other basic software.Anyone else have this issue? I didn't see this in Mojave.Currently im using catalina 10.15.1.

My Device:
Intel i3-6100h with Intel HD 530
4K sharp display

<img width="1382" alt="Screen Shot 2019-11-08 at 6 02 56 PM" src="https://user-images.githubusercontent.com/53279423/68516586-6303f900-0252-11ea-84d2-840ef068032d.png">

**Comment by xxxzc** [comment]
Same with me, no solution found
