### ISSUE TITLE
xps 9550 低配i5，电池状态无法显示

### ISSUE THREAD

**Issue by lavendulaaa** [xxxzc/xps15-9550-macos#36]
你好，我直接用了你提供的OC文件，更新了下SN, MLB and SmUUID，安装都没有问题，其他也都正常只有电池不能显示，请问有什么思路吗？

**Comment by xxxzc** [comment]
系统报告-电源里有信息吗？系统设置-节能器里有没有勾选显示电池状态？

**Comment by lavendulaaa** [comment]
没有电池信息，只有系统电源设置，节能器里也不能勾选，一勾就消失

**Comment by xxxzc** [comment]
emm...之前是否有装过 FakeSMC.kext 或 ACPIBatteryManager.kext 到 SLE 或 LE 中？

**Comment by lavendulaaa** [comment]
我是第一次安装，只用了你提供的文件，后来看电池不能显示上网看了看，装了ACPIBatteryManager到LE也还是没用，很难受，有其他什么步骤会影响吗，比如bios设置之类的

**Comment by xxxzc** [comment]
没遇到过这个问题。。。不装 ACPIBatteryManager，使用 CLOVER 有电池吗？有没有试过别人的配置，比如 wmchris 的

**Comment by lavendulaaa** [comment]
我把config.plist/kernel/add里面VirtualSMC调到SMCBatteryManager前面就好了，好像先后顺序有关系

**Comment by xxxzc** [comment]
感谢
