### ISSUE TITLE
唤醒变重启

### ISSUE THREAD

**Issue by Chillimeat** [xxxzc/xps15-9550-macos#37]
你好我跟你的配置一样，只是是I7的,之前挺好的,这两天不知道做了什么,睡眠之后再次唤醒就变为重启了,我根据网上的配置信息进行了配置,但仍不见效，感谢支持。
我的配置如下:
![image](https://user-images.githubusercontent.com/24307825/69902887-98bd7d00-13cd-11ea-9b5f-ab5ebe46f17f.png)
![image](https://user-images.githubusercontent.com/24307825/69902899-b12d9780-13cd-11ea-9911-3cfe6a8dde6b.png)

**Comment by xxxzc** [comment]
当前的 macos 版本是？具体是什么使用情景下出现这个问题，有连显示器，typec有连设备吗，是合盖睡眠还是自动睡眠出现的问题，点击左上角进入睡眠是否也有这个问题？

`pmset -g log | grep -i failure` 看看，我之前遇到的问题是 `bootroom failure`，完全不明白是什么造成的，系统更新后就好了。

现在则存在两个唤醒重启的问题，一个是 typec 连着显示器进入睡眠，另一个是拔掉 typec 设备后迅速合盖。

另外看下 bootarg 里 darkwake 的值，建议设置成 `darkwake=3`。

**Comment by Chillimeat** [comment]
> 当前的 macos 版本是？具体是什么使用情景下出现这个问题，有连显示器，typec有连设备吗，是合盖睡眠还是自动睡眠出现的问题，点击左上角进入睡眠是否也有这个问题？
> 
> `pmset -g log | grep -i failure` 看看，我之前遇到的问题是 `bootroom failure`，完全不明白是什么造成的，系统更新后就好了。
> 
> 现在则存在两个唤醒重启的问题，一个是 typec 连着显示器进入睡眠，另一个是拔掉 typec 设备后迅速合盖。
> 
> 另外看下 bootarg 里 darkwake 的值，建议设置成 `darkwake=3`。

你好，我的macos10.15 
pmset -g log | grep -i failure发现什么日志都没有，我在config中确实是darkwake=0，我修改一下试试。

**Comment by Chillimeat** [comment]
> > 当前的 macos 版本是？具体是什么使用情景下出现这个问题，有连显示器，typec有连设备吗，是合盖睡眠还是自动睡眠出现的问题，点击左上角进入睡眠是否也有这个问题？
> > `pmset -g log | grep -i failure` 看看，我之前遇到的问题是 `bootroom failure`，完全不明白是什么造成的，系统更新后就好了。
> > 现在则存在两个唤醒重启的问题，一个是 typec 连着显示器进入睡眠，另一个是拔掉 typec 设备后迅速合盖。
> > 另外看下 bootarg 里 darkwake 的值，建议设置成 `darkwake=3`。
> 
> 你好，我的macos10.15
> pmset -g log | grep -i failure发现什么日志都没有，我在config中确实是darkwake=0，我修改一下试试。



> 当前的 macos 版本是？具体是什么使用情景下出现这个问题，有连显示器，typec有连设备吗，是合盖睡眠还是自动睡眠出现的问题，点击左上角进入睡眠是否也有这个问题？
> 
> `pmset -g log | grep -i failure` 看看，我之前遇到的问题是 `bootroom failure`，完全不明白是什么造成的，系统更新后就好了。
> 
> 现在则存在两个唤醒重启的问题，一个是 typec 连着显示器进入睡眠，另一个是拔掉 typec 设备后迅速合盖。
> 
> 另外看下 bootarg 里 darkwake 的值，建议设置成 `darkwake=3`。
我试了下，好像是只有在使用电池的时候才会出现上述情况，如果实现电源则不出现该问题。

**Comment by xxxzc** [comment]
你的配置文件和我的还有什么不一样的地方吗？可以把 cpufrienddataprovider 先去掉试试，这个也有可能导致唤醒变重启

**Comment by Chillimeat** [comment]
> 你的配置文件和我的还有什么不一样的地方吗？可以把 cpufrienddataprovider 先去掉试试，这个也有可能导致唤醒变重启
我使用的cpu是你的配置文件，我看到你在其他问题中提到i7和i5的是一样的架构，所以我直接使用了。
同时我还有另一个问题，就是触摸屏你可以正常使用吗?我发现我的触摸屏不支持多指操作，只能单指使用。

**Comment by xxxzc** [comment]
太久没这个问题，忘了可以用 Console 看 Crash 报告了。。
