### ISSUE TITLE
不重启的话，直接关机再开机会蓝牙不可用

### ISSUE THREAD

**Issue by Coder-Leon** [xxxzc/xps15-9550-macos#38]
需要重启恢复

**Comment by xxxzc** [comment]
![5E1874C223A94A10900DF5EFC052EF3D](https://user-images.githubusercontent.com/22726929/70386896-67e6d480-19d9-11ea-814b-121cd909ed87.jpg)
可以试试小兵的这个方法，用 win+shift 点击

**Comment by Coder-Leon** [comment]
把BRM开头的三个驱动，放/L/E下，重建缓存后好了
