### ISSUE TITLE
睡眠唤醒屏幕不会自己点亮

### ISSUE THREAD

**Issue by Chillimeat** [xxxzc/xps15-9550-macos#39]
你好，睡眠唤醒之后，键盘灯亮，但是屏幕不亮需要滑动鼠标或者键盘才可以实现，启动项中已添加dark=0，有遇到过这个问题吗？？

**Comment by xxxzc** [comment]
是 `dark=0` 没用还是 `darkwake=0` 没用？设置 `darkwake=1` 试试

```
kDarkWakeFlagHIDTickleEarly      = 0x01, // hid tickle before gfx suppression
kDarkWakeFlagHIDTickleLate       = 0x02, // hid tickle after gfx suppression
kDarkWakeFlagHIDTickleNone       = 0x03, // hid tickle is not posted
```

**Comment by Chillimeat** [comment]
> hid tickle before gfx suppression

正解，谢谢，改成1后可以。

**Comment by xxxzc** [comment]
可以的话帮我测试下 darkwake=1 时 长时间睡眠的用电量

**Comment by Chillimeat** [comment]
> 可以的话帮我测试下darkwake = 1时长时间睡眠的用电量

用电量的话，一晚上晚上10点到第二天早上九点，下降20%吧
