### ISSUE TITLE
可以参考一下这个

### ISSUE THREAD

**Issue by inksnw** [xxxzc/xps15-9550-macos#4]
https://www.insanelymac.com/forum/topic/319764-guide-dell-xps-15-9550-mojave-1014x-quick-installation/?page=53
不太懂这个,作者看看有没有可参考的地方,结合一下,

**Comment by xxxzc** [comment]
wmchirs 的 10.14 的教程是从 10.13 改来的，教程本身好像没什么新东西，以前装黑苹果看过很多次了。有空会看看这个贴的评论吧
看了下 Repo 和我的基本没多大差别，有些内容好像还是从我这边过去的
我会尽量追新方法

**Comment by inksnw** [comment]
最新的更新无法开机，换成wmchirs的报上一次开机错误
*** Panic Report ***
panic(cpu 0 caller 0xffffff7f9052d5a8): nvme: "Fatal error occurred. CSTS=0x3
. FW Revision=BXV77D0Q\n"@/BuildRoot/Library/Caches/com.apple.xbs/Sources/IONVMeFamily/IONVMeFamily-387.201.1/IONVMeController.cpp:5307
Backtrace (CPU 0), Frame : Return Address
0xffffff81feaa3a10 : 0xffffff800ddaca1d 
0xffffff81feaa3a60 : 0xffffff800dee6b13 
0xffffff81feaa3aa0 : 0xffffff800ded859a 
0xffffff81feaa3b10 : 0xffffff800dd59ca0 
0xffffff81feaa3b30 : 0xffffff800ddac437 
0xffffff81feaa3c50 : 0xffffff800ddac283 
0xffffff81feaa3cc0 : 0xffffff7f9052d5a8 
0xffffff81feaa3e20 : 0xffffff800e45da67 
0xffffff81feaa3e90 : 0xffffff800e45d989 
0xffffff81feaa3ec0 : 0xffffff800dde8865 
0xffffff81feaa3f40 : 0xffffff800dde8415 
0xffffff81feaa3fa0 : 0xffffff800dd590ce 
      Kernel Extensions in backtrace:
         com.apple.iokit.IONVMeFamily(2.1)[26E33FBA-73DC-3D8A-AA62-16A25FA97C8A]@0xffffff7f90519000->0xffffff7f90557fff
            dependency: com.apple.driver.AppleMobileFileIntegrity(1.0.5)[169BD129-26C1-32E2-82A5-B5E0C1FA99B4]@0xffffff7f8ecf8000
            dependency: com.apple.iokit.IOPCIFamily(2.9)[2CE7BCB3-0766-3A94-A8D4-29BF3EBAEFBC]@0xffffff7f8e695000
            dependency: com.apple.driver.AppleEFINVRAM(2.1)[D872C3C2-611A-3BE6-B3A0-DC8B1A6795F8]@0xffffff7f8edd2000
            dependency: com.apple.iokit.IOStorageFamily(2.1)[499E27C9-AC4D-3239-9FC4-754C7699FA76]@0xffffff7f8eb2a000
            dependency: com.apple.iokit.IOReportFamily(47)[EA2822EA-DACE-34D1-80D1-8EBF65889EBC]@0xffffff7f8f1d1000

BSD process name corresponding to current thread: kernel_task
Boot args: agdpmod=vit9696 brcmfx-country=#a -lilubetaall -v darkwake=no 

*** Panic Report ***
panic(cpu 0 caller 0xffffff7f9052d5a8): nvme: "Fatal error occurred. CSTS=0x3
. FW Revision=BXV77D0Q\n"@/BuildRoot/Library/Caches/com.apple.xbs/Sources/IONVMeFamily/IONVMeFamily-387.201.1/IONVMeController.cpp:5307
Backtrace (CPU 0), Frame : Return Address
0xffffff81feaa3a10 : 0xffffff800ddaca1d 
0xffffff81feaa3a60 : 0xffffff800dee6b13 
0xffffff81feaa3aa0 : 0xffffff800ded859a 
0xffffff81feaa3b10 : 0xffffff800dd59ca0 
0xffffff81feaa3b30 : 0xffffff800ddac437 
0xffffff81feaa3c50 : 0xffffff800ddac283 
0xffffff81feaa3cc0 : 0xffffff7f9052d5a8 
0xffffff81feaa3e20 : 0xffffff800e45da67 
0xffffff81feaa3e90 : 0xffffff800e45d989 
0xffffff81feaa3ec0 : 0xffffff800dde8865 
0xffffff81feaa3f40 : 0xffffff800dde8415 
0xffffff81feaa3fa0 : 0xffffff800dd590ce 
      Kernel Extensions in backtrace:
         com.apple.iokit.IONVMeFamily(2.1)[26E33FBA-73DC-3D8A-AA62-16A25FA97C8A]@0xffffff7f90519000->0xffffff7f90557fff
            dependency: com.apple.driver.AppleMobileFileIntegrity(1.0.5)[169BD129-26C1-32E2-82A5-B5E0C1FA99B4]@0xffffff7f8ecf8000
            dependency: com.apple.iokit.IOPCIFamily(2.9)[2CE7BCB3-0766-3A94-A8D4-29BF3EBAEFBC]@0xffffff7f8e695000
            dependency: com.apple.driver.AppleEFINVRAM(2.1)[D872C3C2-611A-3BE6-B3A0-DC8B1A6795F8]@0xffffff7f8edd2000
            dependency: com.apple.iokit.IOStorageFamily(2.1)[499E27C9-AC4D-3239-9FC4-754C7699FA76]@0xffffff7f8eb2a000
            dependency: com.apple.iokit.IOReportFamily(47)[EA2822EA-DACE-34D1-80D1-8EBF65889EBC]@0xffffff7f8f1d1000

BSD process name corresponding to current thread: kernel_task
Boot args: agdpmod=vit9696 brcmfx-country=#a -lilubetaall -v darkwake=no 

*** Panic Report ***
panic(cpu 0 caller 0xffffff7f9052d5a8): nvme: "Fatal error occurred. CSTS=0x3
. FW Revision=BXV77D0Q\n"@/BuildRoot/Library/Caches/com.apple.xbs/Sources/IONVMeFamily/IONVMeFamily-387.201.1/IONVMeController.cpp:5307
Backtrace (CPU 0), Frame : Return Address
0xffffff81feaa3a10 : 0xffffff800ddaca1d 
0xffffff81feaa3a60 : 0xffffff800dee6b13 
0xffffff81feaa3aa0 : 0xffffff800ded859a 
0xffffff81feaa3b10 : 0xffffff800dd59ca0 
0xffffff81feaa3b30 : 0xffffff800ddac437 
0xffffff81feaa3c50 : 0xffffff800ddac283 
0xffffff81feaa3cc0 : 0xffffff7f9052d5a8 
0xffffff81feaa3e20 : 0xffffff800e45da67 
0xffffff81feaa3e90 : 0xffffff800e45d989 
0xffffff81feaa3ec0 : 0xffffff800dde8865 
0xffffff81feaa3f40 : 0xffffff800dde8415 
0xffffff81feaa3fa0 : 0xffffff800dd590ce 
      Kernel Extensions in backtrace:
         com.apple.iokit.IONVMeFamily(2.1)[26E33FBA-73DC-3D8A-AA62-16A25FA97C8A]@0xffffff7f90519000->0xffffff7f90557fff
            dependency: com.apple.driver.AppleMobileFileIntegrity(1.0.5)[169BD129-26C1-32E2-82A5-B5E0C1FA99B4]@0xffffff7f8ecf8000
            dependency: com.apple.iokit.IOPCIFamily(2.9)[2CE7BCB3-0766-3A94-A8D4-29BF3EBAEFBC]@0xffffff7f8e695000
            dependency: com.apple.driver.AppleEFINVRAM(2.1)[D872C3C2-611A-3BE6-B3A0-DC8B1A6795F8]@0xffffff7f8edd2000
            dependency: com.apple.iokit.IOStorageFamily(2.1)[499E27C9-AC4D-3239-9FC4-754C7699FA76]@0xffffff7f8eb2a000
            dependency: com.apple.iokit.IOReportFamily(47)[EA2822EA-DACE-34D1-80D1-8EBF65889EBC]@0xffffff7f8f1d1000

BSD process name corresponding to current thread: kernel_task
Boot args: agdpmod=vit9696 brcmfx-country=#a -lilubetaall -v darkwake=no

**Comment by xxxzc** [comment]
@inksnw 
把 NvmExpressDxe-64.efi 加回来了，测试了几次好像没问题。
感谢~

**Comment by inksnw** [comment]
还是不行
Kernel Extensions in backtrace:
         com.apple.iokit.IONVMeFamily(2.1)[26E33FBA-73DC-3D8A-AA62-16A25FA97C8A]@0xffffff7f8ff19000->0xffffff7f8ff57fff
            dependency: com.apple.driver.AppleMobileFileIntegrity(1.0.5)[169BD129-26C1-32E2-82A5-B5E0C1FA99B4]@0xffffff7f8e6f8000
            dependency: com.apple.iokit.IOPCIFamily(2.9)[2CE7BCB3-0766-3A94-A8D4-29BF3EBAEFBC]@0xffffff7f8e095000
            dependency: com.apple.driver.AppleEFINVRAM(2.1)[D872C3C2-611A-3BE6-B3A0-DC8B1A6795F8]@0xffffff7f8e7d2000
            dependency: com.apple.iokit.IOStorageFamily(2.1)[499E27C9-AC4D-3239-9FC4-754C7699FA76]@0xffffff7f8e52a000
            dependency: com.apple.iokit.IOReportFamily(47)[EA2822EA-DACE-34D1-80D1-8EBF65889EBC]@0xffffff7f8ebd100

**Comment by xxxzc** [comment]
确实不是 NvmExpressDxe-64.efi 的问题，这个是给不支持 nvme 的 bios 用的。
我之前也出现过一模一样的问题，但现在实在无法再复现。

**Comment by xxxzc** [comment]
> 还是不行
> Kernel Extensions in backtrace:
> com.apple.iokit.IONVMeFamily(2.1)[26E33FBA-73DC-3D8A-AA62-16A25FA97C8A]@0xffffff7f8ff19000->0xffffff7f8ff57fff
> dependency: com.apple.driver.AppleMobileFileIntegrity(1.0.5)[169BD129-26C1-32E2-82A5-B5E0C1FA99B4]@0xffffff7f8e6f8000
> dependency: com.apple.iokit.IOPCIFamily(2.9)[2CE7BCB3-0766-3A94-A8D4-29BF3EBAEFBC]@0xffffff7f8e095000
> dependency: com.apple.driver.AppleEFINVRAM(2.1)[D872C3C2-611A-3BE6-B3A0-DC8B1A6795F8]@0xffffff7f8e7d2000
> dependency: com.apple.iokit.IOStorageFamily(2.1)[499E27C9-AC4D-3239-9FC4-754C7699FA76]@0xffffff7f8e52a000
> dependency: com.apple.iokit.IOReportFamily(47)[EA2822EA-DACE-34D1-80D1-8EBF65889EBC]@0xffffff7f8ebd100

有试了好几次，我现在可以 99% 确定是因为缺少 **SSDT-XHCI_Syspref.aml**，可以帮忙确定下吗:)

**Comment by inksnw** [comment]
好吧,那还是先用着wmchris的吧

**Comment by inksnw** [comment]
已经可以正常使用，感谢

**Comment by xxxzc** [comment]
> 已经可以正常使用，感谢

更新了一下，改用了 corenel 的 SSDT/DSDT。
感觉之前那个 `USBPort.kext` 有问题，主要是睡眠唤醒后 USB 设备无响应以及在热插拔 typec 设备后 Console 会疯狂输出信息导致睡眠失败。
现在这个简单测试下都很正常的。如果有时间麻烦使用测试一下，谢了~
