### ISSUE TITLE
电池模式下，锁屏后唤醒大概率出现黑屏情况

### ISSUE THREAD

**Issue by Coder-Leon** [xxxzc/xps15-9550-macos#40]
只有键盘背光和屏幕背光，黑屏。

**Comment by xxxzc** [comment]
经常电池模式睡眠唤醒，刚才试了几次，没出现过。。
可以试试：
1. 启动参数添加 `-igfxmlr -igfxhdmidivs `
2. 注入 EDID 

参考 [FAQ.IntelHD.cn](https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.cn.md)

**Comment by Coder-Leon** [comment]
> 经常电池模式睡眠唤醒，刚才试了几次，没出现过。。
> 可以试试：
> 
> 1. 启动参数添加 `-igfxmlr -igfxhdmidivs `
> 2. 注入 EDID
> 
> 参考 [FAQ.IntelHD.cn](https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.cn.md)

添加 -igfxmlr 后，开机直接黑屏

**Comment by Coder-Leon** [comment]
1080P机器，之前开启过HIDPI，注入过EDID

**Comment by xxxzc** [comment]
那有没有可能是之前的 EDID 不再可用？删除掉 `/System/Library/Displays/Contents/Resources/Overrides` 试试？（备份下，不确定内置的显示器会不会重新生成，外置显示器删除后会重新生成）
