### ISSUE TITLE
电池默认声音问题

### ISSUE THREAD

**Issue by jioswu** [xxxzc/xps15-9550-macos#41]
耳机模式AppleALC 换到1.4.2或者更新到1.4.4一样会有声音失真的问题,需要把输入改为线路输入就可以,请问这个问题有办法解决么

**Comment by xxxzc** [comment]
之前参考教程整理了下 ALC298 的节点，试了多种 configdata，都没有用，应该还得调整 layout.xml 和 platform.xml 。。。

最近比较忙，下周末再研究一下

**Comment by xxxzc** [comment]
发现是 0x18 节点（Line In）会自动掉电平（0x22 -> 0x02），原因未知，各种尝试都没用。

还是把 layout id 改为 72，用 [ComboJack](https://github.com/hackintosh-stuff/ComboJack/tree/master/ComboJack_Installer) 吧：

1. 删除 CodecCommander.kext 和 ALCPlugFix
2. 用回官方的 AppleALC.kext
3. 把 VerbStub.kext 放到 kext 里
4. install.sh

参考 [KNNSpeed 的 post](https://www.tonymacx86.com/threads/guide-dell-xps-15-9560-4k-touch-1tb-ssd-32gb-ram-100-adobergb.224486/page-9)

**Comment by xxxzc** [comment]
似乎用 [ALCPlugFix](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/tree/master/ALCPlugFix) 也有效？AppleALC 实际上可以和它一样在初始化的时候发送一个激活 Line In 的 configdata，但直接用 AppleALC 发却没法避免失真。

可以帮忙测试一下。

**Comment by duguhu007** [comment]
> 似乎用 [ALCPlugFix](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/tree/master/ALCPlugFix) 也有效？AppleALC 实际上可以和它一样在初始化的时候发送一个激活 Line In 的 configdata，但直接用 AppleALC 发却没法避免失真。
> 
> 可以帮忙测试一下。

使用了这个好像可以,待我多用几天再回复

**Comment by jioswu** [comment]
> 似乎用 [ALCPlugFix](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/tree/master/ALCPlugFix) 也有效？AppleALC 实际上可以和它一样在初始化的时候发送一个激活 Line In 的 configdata，但直接用 AppleALC 发却没法避免失真。
> 
> 可以帮忙测试一下。

使用了这个好像可以,待我多用几天再回复

**Comment by jioswu** [comment]
> 似乎用 [ALCPlugFix](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/tree/master/ALCPlugFix) 也有效？AppleALC 实际上可以和它一样在初始化的时候发送一个激活 Line In 的 configdata，但直接用 AppleALC 发却没法避免失真。
> 
> 可以帮忙测试一下。

没有作用,还是会在使用电池的时候出现破音

**Comment by xxxzc** [comment]
@duguhu007 那还是用 combojack 吧，这个肯定没问题

**Comment by ATFieldBeast** [comment]
> 之前参考教程整理了下 ALC298 的节点，试了多种 configdata，都没有用，应该还得调整 layout.xml 和 platform.xml 。。。
> 
> 最近比较忙，下周末再研究一下

smallssnow在[他的repo里](https://github.com/smallssnow/XPS9570-8570H-macos)提出了30和72都有问题，然后他搞了个32提交给AppleALC，那边也添加了[ALC298](https://github.com/acidanthera/AppleALC/blob/master/Resources/ALC298/layout32.xml)，可以试试看?我也是才看到还没试过，也不知道大佬之前有研究过这个没有

**Comment by xxxzc** [comment]
@ATFieldBeast 30 和 32 没太大区别，都没法阻止使用过程中 0x18 节点突然掉电。
他对 72 的描述是错误的，knnspeed 大佬的 72 没有给输入节点是因为他另外写了个 ComboJack 在插入耳机的时候重新选择是 Headset （使用 0x18）， Headphone（不使用 0x18 和 0x1a）还是 LineIn（使用 0x1a 屏蔽 0x21）。

**Comment by ATFieldBeast** [comment]
> @ATFieldBeast 30 和 32 没太大区别，都没法阻止使用过程中 0x18 节点突然掉电。
> 他对 72 的描述是错误的，knnspeed 大佬的 72 没有给输入节点是因为他另外写了个 ComboJack 在插入耳机的时候重新选择是 Headset （使用 0x18）， Headphone（不使用 0x18 和 0x1a）还是 LineIn（使用 0x1a 屏蔽 0x21）。

好的谢谢大佬（不过我发现我用了32之后是直接没声了，所以又换回了30
