### ISSUE TITLE
请问屏幕支持多指操作吗？

### ISSUE THREAD

**Issue by Chillimeat** [xxxzc/xps15-9550-macos#43]
我的屏幕只支持单指操作，多指操作不能识别，你的这样吗？

**Comment by xxxzc** [comment]
我的可以单指选择和拖动窗口，双指滑动和缩放。但是双指滑动很容易识别成点击，不好用。
写了个开启触摸屏 GPIO Pinning 的补丁（感觉没什么改善），可以试试。

[SSDT-TPLX.aml.zip](https://github.com/xxxzc/xps15-9550-macos/files/3991487/SSDT-TPLX.aml.zip)

---

Edit: 触摸屏好像并没有用到 TPL 设备，上面那个 SSDT 应该啥作用也没有。
