### ISSUE TITLE
AppleNVMe: Assert failed error

### ISSUE THREAD

**Issue by fttx** [xxxzc/xps15-9550-macos#44]
Hi, i tried to boot using Clover, and I've got an error saying "AppleNVMe: Assert failed".
I've fixed it by enabling USB/FixOwnership and USB/Inject. Any Idea why is this happening? I've a 512GB Toshiba SSD.

**Comment by xxxzc** [comment]
Do you have `BIOS-Advanced Boot Options-Enable Legacy Option ROMs` enabled? In my test, if it is enabled, my laptop will stuck at boot and can be fixed by enabling `FixOwnership`.

As CLOVER described:

```
FixOwnership(VOID)
/*++
 
 Routine Description:
 Disable the USB legacy Support in all Ehci and Uhci.
 This function assume all PciIo handles have been created in system.
 Slice - added also OHCI and more advanced algo. Better then known to Intel and Apple :)
```

**Comment by fttx** [comment]
Yes, it was enabled, now that is off it's booting properly, thank you!

I've also noticed that your KernelToPatch section is empty and also the DSDT Patches section has far fewer items compared to the wmchris configuration, why is that?

**Comment by xxxzc** [comment]
wmchris is providing a stable and more compatible configuration while my goal is to minimize the configuration.

1. Some SSDT/patches are definitely not needed according to the installation guide of some extensions: igpu, audio and usb
2. Some can be replaced with SSDT tricks: OSI, STA, CRS... see [Changelog.md#ssdts](https://github.com/xxxzc/xps15-9550-macos/blob/master/Changelog.md#ssdts)(may be a lot of grammatical errors)
3. Some may not be needed after my testing: PTSWAK, UPRW...

**Comment by asert1echo** [comment]
can anyone make a simple explanation
