### ISSUE TITLE
Wake after sleep produces a reboot

### ISSUE THREAD

**Issue by fttx** [xxxzc/xps15-9550-macos#46]
Hi, i've an XPS15 9550 FHD i7-6700hq, and i think i've an issue similar to: #37

Basically, whenever I wake up the system it will show a black screen and after some time boot up. 

log:
![image](https://user-images.githubusercontent.com/5663423/71444911-72ada300-2715-11ea-8195-54e0e50da8dd.png)

I've set the parameter with pmset and set the Energy Saver settings correctly. 
I've the exact config folder of the repository except for the config.plist/Graphics/EDID Injection parameter.

**Comment by xxxzc** [comment]
Are you using VoodooI2C 2.3? It will cause reboot after wake.
https://github.com/alexandred/VoodooI2C/issues/231

**Comment by fttx** [comment]
Yes, I reverted to 2.2, and it's working now, thank you!
