### ISSUE TITLE
电池剩余电量显示不正常

### ISSUE THREAD

**Issue by moyuwangP** [xxxzc/xps15-9550-macos#47]
![74D7F1EB-C378-4A7F-B153-6329608B4856](https://user-images.githubusercontent.com/14159495/71950200-a7007500-3193-11ea-98fe-2183d6d358ef.png)
从较多的电量一下降到6%

**Comment by xxxzc** [comment]
有可能是 EC 的问题，删除 SSDT-EC，使用

```
<dict>
					<key>Comment</key>
					<string>Rename ECDV to EC</string>
					<key>Disabled</key>
					<false/>
					<key>Find</key>
					<data>
					RUNEVg==
					</data>
					<key>Replace</key>
					<data>
					RUNfXw==
					</data>
				</dict>
```

试试

**Comment by moyuwangP** [comment]
是把这一段加到Config.plis里吗
试了一下直接进不了系统了
好像是卡在载入.kext上了

**Comment by moyuwangP** [comment]
好像是我电脑的电池或者电源管理出问题了
