### ISSUE TITLE
触控板不工作

### ISSUE THREAD

**Issue by moyuwangP** [xxxzc/xps15-9550-macos#48]
可以把https://github.com/wmchris/DellXPS15-9550-OSX/tree/10.15/10.15/CLOVER/kexts/Other/VoodooPS2Controller.kext 复制到 ../CLOVER/kexts/Other来修复问题

**Comment by xxxzc** [comment]
重建缓存也不行么？

**Comment by moyuwangP** [comment]
在安装程序里触控板就没法用
进系统之后偏好设置里显示找不到触控板

**Comment by xxxzc** [comment]
安装和刚进入系统是识别不到触摸板的，需要
```
sudo kextcache -i /
```

VoodooPS2Controller 的触摸板驱动走的是 PS2，而 XPS15 的触摸板是 I2C 设备。
