### ISSUE TITLE
High battery usage

### ISSUE THREAD

**Issue by fttx** [xxxzc/xps15-9550-macos#49]
Since the latest release, i noticed an increased battery discharge rate.
Are these values in range?
![image](https://user-images.githubusercontent.com/5663423/72426092-63a49880-3789-11ea-85a1-ab4719c494c5.png)

**Comment by xxxzc** [comment]
Replace CPUFriendDataProvider.kext with [this one](https://github.com/xxxzc/xps15-9550-macos/releases/download/1911/CPUFriendDataProvider.kext.zip) may reduce battery usage

**Comment by fttx** [comment]
Ok, i will test it. Any idea on how to clear the replace battery warning?
<img width="780" alt="Screen Shot 2020-01-18 at 16 12 01" src="https://user-images.githubusercontent.com/5663423/72665905-44b63880-3a0d-11ea-8e03-89339b33e301.png">
