### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by frankbird2b** [xxxzc/xps15-9550-macos#5]
试过楼主的efi文件夹，一直都是 couldn't allocate runtime area,查找教程算过slice值，也替换过各种OsxAptioFixDrv，均无效，头大

**Comment by xxxzc** [comment]
用别人的正常么，比如 https://github.com/wmchris/DellXPS15-9550-OSX

**Comment by frankbird2b** [comment]
楼主你最新的efi能进clover,但是看不到usb的安装盘

**Comment by xxxzc** [comment]
添加 osxfatbinarydrv.efi 和 hfsplus.efi 应该能解决

**Comment by frankbird2b** [comment]
已安装成功，感谢

**Comment by frankbird2b** [comment]
基本一切正常，最后主要有两个问题 1 新系统没有原来10.13流畅 2 电脑静止一段时间后没有显示，但是其实还在正常运转。外接显示器后两个显示器均显示正常，但是合上笔记本盖子后重新打开笔记本盖子外接显示器仍然正常，笔记本本身黑屏，有背光。不知道楼主能否帮助解决。非常感谢楼主，已经非常完美了

**Comment by xxxzc** [comment]
> 基本一切正常，最后主要有两个问题 1 新系统没有原来10.13流畅 2 电脑静止一段时间后没有显示，但是其实还在正常运转。外接显示器后两个显示器均显示正常，但是合上笔记本盖子后重新打开笔记本盖子外接显示器仍然正常，笔记本本身黑屏，有背光。不知道楼主能否帮助解决。非常感谢楼主，已经非常完美了

目前先使用 wmchris 的吧，他的比较完美，唯一需要做的就是把 ACPI/Patched 里的 SSDT-BATC.aml 删了。
我的遇到了一个很奇怪的问题，可能会很长时间不更新。

**Comment by frankbird2b** [comment]
好的，感谢您的付出

**Comment by frankbird2b** [comment]
楼主最新的包和wmchris的均无法进系统，还是老问题couldn't allocate runtime area，我还是用之前的包吧，这是唯一能正常使用的了

**Comment by xxxzc** [comment]
> 楼主最新的包和wmchris的均无法进系统，还是老问题couldn't allocate runtime area，我还是用之前的包吧，这是唯一能正常使用的了

couldn't allocate runtime area 是一直会，还是偶尔会？
我更新了一下，现在暂时还没有遇到启动的问题，睡眠正常，外接显示器合盖再打开也正常
之前的睡眠问题应该是 USB 接口疯狂报错造成的
如果有空麻烦帮忙测试一下，谢啦~

**Comment by inksnw** [comment]
睡眠直接睡关机了

**Comment by xxxzc** [comment]
> 睡眠直接睡关机了

额，你有设置 hibernatemode 么，或者用 sudo pmset -g custom 以及 Console.app 系统报告 看看是什么阻止了睡眠

**Comment by frankbird2b** [comment]
> > 楼主最新的包和wmchris的均无法进系统，还是老问题couldn't allocate runtime area，我还是用之前的包吧，这是唯一能正常使用的了
> 
> couldn't allocate runtime area 是一直会，还是偶尔会？
> 我更新了一下，现在暂时还没有遇到启动的问题，睡眠正常，外接显示器合盖再打开也正常
> 之前的睡眠问题应该是 USB 接口疯狂报错造成的
> 如果有空麻烦帮忙测试一下，谢啦~

测试了，还是老问题 couldn't allocate runtime area，没办法更深入了

**Comment by frankbird2b** [comment]
> > > 楼主最新的包和wmchris的均无法进系统，还是老问题couldn't allocate runtime area，我还是用之前的包吧，这是唯一能正常使用的了
> > 
> > 
> > couldn't allocate runtime area 是一直会，还是偶尔会？
> > 我更新了一下，现在暂时还没有遇到启动的问题，睡眠正常，外接显示器合盖再打开也正常
> > 之前的睡眠问题应该是 USB 接口疯狂报错造成的
> > 如果有空麻烦帮忙测试一下，谢啦~
> 
> 测试了，还是老问题 couldn't allocate runtime area，没办法更深入了

用了这么多的包，现在唯一能成功的就是楼主之前的老包了。黑屏问题经测试是电脑放至一段时间自然黑屏，但是背光还有。找不到 couldn't allocate runtime area的原因，各种方法都用尽了。

**Comment by xxxzc** [comment]
@frankbird2b 

couldn't allocate runtime area 解决方法一般就两个([Here](https://github.com/wmchris/DellXPS15-9550-OSX/tree/10.14/10.14/CLOVER/drivers64UEFI/other))

1. 使用 AptioMemoryFix，它会自动计算 slide
2. 使用 OsxAptioFix3Drv-64.efi 或 OsxAptioFix2Drv-64.efi  并手动计算 slide

上面两个不能同时使用，也不能和 OsxLowMemFix 一起用

自然黑屏后无法唤醒的问题是用的最新的包还是之前的老包？我用最新的测试了下没出现此问题。使用电池睡眠后别说背光连电源指示灯都灭了，按电源键就正常 唤醒没出现啥问题= =。

**Comment by frankbird2b** [comment]
之前试过不行的，不过我有空会再试。感谢你耐心帮助。也许只是我电脑特例吧

**Comment by xxxzc** [comment]
> 之前试过不行的，不过我有空会再试。感谢你耐心帮助。也许只是我电脑特例吧

使用 AptioMemoryFix 时候看看上面关于内存的提示信息是啥？
你不是说有可以用的包么，把他的替换过来试试？
是不是都试过了= =

**Comment by frankbird2b** [comment]
> > 之前试过不行的，不过我有空会再试。感谢你耐心帮助。也许只是我电脑特例吧
> 
> 使用 AptioMemoryFix 时候看看上面关于内存的提示信息是啥？
> 你不是说有可以用的包么，把他的替换过来试试？
> 是不是都试过了= =

楼主最新包的OsxAptioFixDrv2，OsxAptioFixDrv3加slide值145均无效。AptioMemoryFix的话会提示
AMF: No slide values are usable!Falling back to 145 with 0x17DDF000 bytes!

**Comment by kingkelo** [comment]
我也是couldn't allocate runtime area,并且睡眠唤醒黑屏

**Comment by xxxzc** [comment]
@frankbird2b @kingkelo https://github.com/acidanthera/AptioFixPkg 这里的方法有都试过吗？
@kingkelo 你是在用 4k 屏么，我的 1080p 屏是正常的，今天换上 4k 试了下睡眠直接重启

**Comment by frankbird2b** [comment]
> @frankbird2b @kingkelo https://github.com/acidanthera/AptioFixPkg 这里的方法有都试过吗？
> @kingkelo 你是在用 4k 屏么，我的 1080p 屏是正常的，今天换上 4k 试了下睡眠直接重启

看了一下，好像没讲什么方法？还有我也是4K屏幕

**Comment by frankbird2b** [comment]
楼主最新的文件已解决之前的所有 问题哟，一切正常使用，非常感谢楼主的分享，我的黑苹果跟白苹果效果差不多了哈哈
