### ISSUE TITLE
No internet connectivity on initial install

### ISSUE THREAD

**Issue by vhbert** [xxxzc/xps15-9550-macos#50]
I've tried installing Mac OS with the kexts and drivers you provided and I do in fact manage to boot onto my USB to the Mac OS installer (with Clover).
But I don't have any WiFi connectivity, so I can't proceed with the install,

Any ideas?

**Comment by xxxzc** [comment]
Network is not required to install macOS, just skip it.

**Comment by vhbert** [comment]
I figured it out, thanks again for making this repository accessable to the public.
