### ISSUE TITLE
High GPU usage after sleep

### ISSUE THREAD

**Issue by tiger511** [xxxzc/xps15-9550-macos#53]
GPU usage stays at full (350MHz) at idle when i resume from sleep.I think this is also the reason why display flashes every 5minutes.This happens with both Clover & OC.
<img width="404" alt="Screen Shot 2020-03-19 at 5 35 20 PM" src="https://user-images.githubusercontent.com/53279423/77063786-801eb480-6a08-11ea-8059-d6b75aa8233d.png">

**Comment by tiger511** [comment]
This is very hard to reproduce.But it happens when i use the laptop for few hours then put it to sleep.Then it resumes, the GPU stays at full load at idle and the bottom warms up.A restart fixes the issue temporarily until the next sleep/resume cycle.

**Comment by xxxzc** [comment]
350MHz is the basic frequency.
https://www.intel.com/content/www/us/en/support/products/88345/graphics-drivers/graphics-for-6th-generation-intel-processors/intel-hd-graphics-530.html

**Comment by tiger511** [comment]
> 350MHz is the basic frequency.
> https://www.intel.com/content/www/us/en/support/products/88345/graphics-drivers/graphics-for-6th-generation-intel-processors/intel-hd-graphics-530.html

Yes...but it should usually be at 0Mhz.When i restart the laptop its at 0Mhz...it clocks up when in used...then it should clock back to zero.

**Comment by tiger511** [comment]
It should be like this:
<img width="403" alt="Screen Shot 2020-03-21 at 12 09 17 PM" src="https://user-images.githubusercontent.com/53279423/77220689-d4db4000-6b6c-11ea-9691-e0a185852438.png">

**Comment by tiger511** [comment]
Seems like loading AppleGuC with latest WhateverGreen  will fix this issue.Because that is the only way to get native power management.I don't have the device anymore to test if AppleGuC loads with skylake hardware.Anyone seeing this issue,try: **igfxfw=2** boot args.if it boots successfully,the problem should be solved.If it doesn't boot,then currently there is no solution to this.
