### ISSUE TITLE
update.py 自动更新OC 0.5.7 后启动失败

### ISSUE THREAD

**Issue by zhongjun96** [xxxzc/xps15-9550-macos#55]
检查是OC 0.5.7 有几个驱动改名了，能否更新脚本，支持OC 0.5.7

**Comment by xxxzc** [comment]
能否帮忙测试一下这个 OC 0.5.9 是否正常，音频是否正常，以及 HDMI 和 HDMI 音频是否正常？
[XPS15-9550-OC-059_TEST.zip](https://github.com/xxxzc/xps15-9550-macos/files/4723855/XPS15-9550-OC-059_TEST.zip)

**Comment by zhongjun96** [comment]
@xxxzc 😁抱歉，已经换电脑了，忘记关闭问题了。
