### ISSUE TITLE
XPS 9550

### ISSUE THREAD

**Issue by feldkurat** [xxxzc/xps15-9550-macos#57]
XPS 9550 (Precision 5510 in fact) / 10.15.5  - touchpad does not work. May you suggest possible fix ? Thank you :)

**Comment by xxxzc** [comment]
Please try [XPS15-9550-OC-2006-TEST.zip](https://github.com/xxxzc/xps15-9550-macos/files/4759805/XPS15-9550-OC-2006-TEST.zip) or 
[XPS15-9550-CLOVER-2006-TEST.zip](https://github.com/xxxzc/xps15-9550-macos/files/4759812/XPS15-9550-CLOVER-2006-TEST.zip)

**Comment by feldkurat** [comment]
Thank you! After few reboots release 2004 started to work (of course I needed USB mouse to handle setup & postinstall).

**Comment by xxxzc** [comment]
I guess you didn't rebuild kextcache: `sudo kextcache -i /`.

btw, can you help me test 2006's hdmi and hdmi audio?

**Comment by feldkurat** [comment]
Yes
On the upcoming weekend

**Comment by feldkurat** [comment]
With 2006 test release:
HDMI works only if I connect cable after booting. No HDMI audio (no corresponding output audio device).

I did not test it with 2004 release.

Should I send any log file to you ?

**Comment by xxxzc** [comment]
Thank you! 

I know what the problem is.
