### ISSUE TITLE
下载了OC的config.plist，拖入U盘的efi文件夹中，OC引导出错

### ISSUE THREAD

**Issue by tiange1949** [xxxzc/xps15-9550-macos#58]
错误显示：achi error：Method parse/execution failed(GPRW)。
经过谷歌查询，说是缺少dsdt的热补丁，于是在config.plist加入了如下设置
![](https://tommydai-1255332951.cos.ap-shanghai.myqcloud.com/20200608000959.png)
重新进入U盘启动，选择从install from macOS Catalina，依旧出现这个问题。
求问大佬，这种问题一般有什么解决办法吗

**Comment by tiange1949** [comment]
ACPI-add中的aml文件已经找到并拖入到相应的文件夹
![image](https://user-images.githubusercontent.com/26919925/83974018-c35c3580-a91c-11ea-903a-79dbe2d8b648.png)

**Comment by tiange1949** [comment]
- U盘EFI文件目录如下（packages.csv中的kext和efi文件都已下载）：

![](https://tommydai-1255332951.cos.ap-shanghai.myqcloud.com/20200608001628.png)

- packages清单如下：
![](https://tommydai-1255332951.cos.ap-shanghai.myqcloud.com/packages.png)

**Comment by tiange1949** [comment]
![](https://tommydai-1255332951.cos.ap-shanghai.myqcloud.com/packages.png)

**Comment by xxxzc** [comment]
请直接用这个包试一下，如果有 HDMI 的话，麻烦帮忙测试一下 HDMI 和 HDMI 音频是否正常：
[XPS15-9550-OC-2006-TEST.zip](https://github.com/xxxzc/xps15-9550-macos/files/4759778/XPS15-9550-OC-2006-TEST.zip)

如果这个包有问题，建议先用 [这个包](https://github.com/xxxzc/xps15-9550-macos/releases/tag/2004)，你用的那个有很多无用的 ACPI 补丁。

**Comment by xxxzc** [comment]
注：不要使用 OCC 修改配置，使用文本编辑器或者代码编辑器

可以加我 QQ：289833376

**Comment by tiange1949** [comment]
首先非常感谢大佬，让我这个小白也成功安装上了黑苹果，下面我向大佬汇报一下我的各个驱动情况：

- USB 3.0 驱动正常，但是插入 U 盘未开启高速传输，原因未明；
![](https://raw.githubusercontent.com/tiange1949/Image-hosting-service/master/USB3.0%E6%8E%A5%E5%8F%A3.png)

- wifi 蓝牙正常，毕竟 DW1830 免驱
![](https://raw.githubusercontent.com/tiange1949/Image-hosting-service/master/wifi.png)

- 耳机和扬声器正常，**hdmi 未识别**，下载了 Combo-Jackmaster，未发现耳机爆音；
![](https://raw.githubusercontent.com/tiange1949/Image-hosting-service/master/%E8%80%B3%E6%9C%BA%E6%AD%A3%E5%B8%B8%20hdmi%20%E6%9C%AA%E8%AF%86%E5%88%AB.png)
![](https://raw.githubusercontent.com/tiange1949/Image-hosting-service/master/%E6%A3%80%E6%9F%A5%E5%86%85%E5%BB%BA%E5%A3%B0%E5%8D%A1%E6%98%AF%E5%90%A6%E6%BF%80%E6%B4%BB.png)

- 集成显卡正常，硬件加速已开启；
![](https://raw.githubusercontent.com/tiange1949/Image-hosting-service/master/%E6%98%BE%E5%8D%A1%E9%A9%B1%E5%8A%A8%E6%AD%A3%E5%B8%B8.png)
![](https://raw.githubusercontent.com/tiange1949/Image-hosting-service/master/%E6%A3%80%E6%9F%A5%E9%BB%91%E8%8B%B9%E6%9E%9C%E6%98%BE%E5%8D%A1%E5%BC%80%E5%90%AF%E7%A1%AC%E4%BB%B6%E5%8A%A0%E9%80%9F.png)

- 读卡器未识别，这个冒似无解；

- 雷电 3 接口未识别；
![](https://raw.githubusercontent.com/tiange1949/Image-hosting-service/master/thunderboot%203.png)

- 睡眠正常这个不知道如何检测；

- 不知道如何关闭开机代码界面，EFI 目录和OCC 配置界面如下：
![](https://raw.githubusercontent.com/tiange1949/Image-hosting-service/master/EFI_Document_Directory.png)
![](https://raw.githubusercontent.com/tiange1949/Image-hosting-service/master/OCC_Config_Scheme.png)

**具体情况就是这样，期待大佬给小白解惑！**

**Comment by tiange1949** [comment]
另外还有一个问题，屏幕（4k 屏）会出现短短的白线，在黑色背景下看得很清晰，白色背景同色看不到，目前猜测两个原因：
- 屏幕驱动有问题；
- 屏幕本身出问题了；
