### ISSUE TITLE
配置基本和你一样只是显示屏不是4K的，无限重启

### ISSUE THREAD

**Issue by xinjing-cloud** [xxxzc/xps15-9550-macos#59]
大佬，小弟配置基本和您一样，只是屏幕是1080P。通过您提供的EFI，基本上10次9次启动不了。启动到Brcmpatchram:Processing time *** secends。然后就会自动重启，不管是Clover还是OC都是这样的情况。

**Comment by xxxzc** [comment]
有没有试试清除nvram

**Comment by xinjing-cloud** [comment]
出现这个问题后我把BIOS也升级到了最新的版本。当然也做了清除NVRAM。

**Comment by xxxzc** [comment]
屏幕上的信息能否再给多一些，当这一条不好断定问题

**Comment by xinjing-cloud** [comment]
因为会一闪而过，后来拍了视频发现是nvme的驱动问题，更换了一个东芝的固态硬盘就好了。谢谢
