### ISSUE TITLE
Please refer to the tutorial, not only the repository

### ISSUE THREAD

**Issue by krim404** [xxxzc/xps15-9550-macos#6]
Hello,
i see you referenced my repository in your tutorial, sadly some people misunderstood your text and took it literaly - they used your tutorial with my files.

Obviously this results in a non working enviroment and they post bug reports on my repo.
Any chance to either inform them, that they should also read the tutorial when using my files?

**Comment by xxxzc** [comment]
Hi. Sorry for that.
I deleted the following message from my README.md.

> If you encounter any problem with my clover files, please 1. create a issue and 2. use [wmchris/DellXPS15-9500-OSX](https://github.com/wmchris/DellXPS15-9550-OSX) instead, witch is more stable. 

But there is another reference refers to the use of your `AppleBacklightInjector.kext`, is that ok?

By the way, I think the previous framebuffer patching and `USBPort.kext` are incorrect. 
1. 4k display can't sleep/wake functionally
2. USB devices not response when wake in battery mode

So I generated a new one: https://github.com/xxxzc/xps15-9550-macos/commit/2f7e894acc400414fbf232cbc66c5b9cb116dafd, and it works.

**Comment by krim404** [comment]
I cannot confirm the 4k display sleep/wake functionality bug. works like a charm for me with the basic patches from insanelymac. 

Are you sure to ditch the UB31 patch from the kext? I'll start the usb device lookup process in a few minutes to check this.

**Comment by krim404** [comment]
yep you're right, UB31 is not in XHC, but in TBTU. So no need for them to be in the file

**Comment by xxxzc** [comment]
> I cannot confirm the 4k display sleep/wake functionality bug. works like a charm for me with the basic patches from insanelymac.

`AAAbGQ==` also works for `i5-6300HQ`, since it has the same `HD 530` iGPU as i7s have, and I can confirm `BgAbGQ==` is a bad one for i5.

Besides, for `i5-6300HQ`, `framebuffer-unifiedmem` should be set to `AAAAgA==` to enable 2048MB VRAM.

**Comment by krim404** [comment]
Using the 0x1916 with i7 had multiple issues in the past like screen flickering.
 because most dells in the European Union are shipped with i7 I use this as default.
Strangely 191b0006, which worked well with the old setup produces your described bug on i7, too.

Btw if possible you should stick to 1,5gb mem (unless it is reserved anyway). More than enough mem and closer to a real MacBook - just in case you have to do screen sharing with an apple employee ;)

**Comment by xxxzc** [comment]
> Using the 0x1916 with i7 had multiple issues in the past like screen flickering.
> because most dells in the European Union are shipped with i7 I use this as default.
> Strangely 191b0006, which worked well with the old setup produces your described bug on i7, too.
> 
> Btw if possible you should stick to 1,5gb mem (unless it is reserved anyway). More than enough mem and closer to a real MacBook - just in case you have to do screen sharing with an apple employee ;)

What I mean is i5 can use 0x191b, no need to change it to 0x1916.
Thanks for your suggestions~

**Comment by krim404** [comment]
Sorry Thought you referred to the value you used in 2f7e894.
No more screen flickering, especially by playing hardware accelerated videos? Don’t have a i5 XPS close to check by myself.

Thank you for the information :)
