### ISSUE TITLE
声卡无法驱动

### ISSUE THREAD

**Issue by chenyaokaiccc** [xxxzc/xps15-9550-macos#60]
您好，我的配置和您的一样，只是屏幕是1080p，安装以后，其他基本完美，就是笔记本没有声音，应该是声卡没有驱动，所以想问您声卡仿冒layout ID？我试一下，或者具体解决方法，谢谢您！

**Comment by xxxzc** [comment]
装了 combojack 也没有嘛？https://github.com/xxxzc/xps15-9550-macos#headphone

**Comment by chenyaokaiccc** [comment]
换了OC，解决了频率问题后，现在使用完美，谢谢大大的付出
