### ISSUE TITLE
CPU频率锁定800mhz

### ISSUE THREAD

**Issue by chenyaokaiccc** [xxxzc/xps15-9550-macos#61]
Opencore引导，cpu无法正常变频一直锁频800mhz，试了很多方法都不行，重建了cpufriendprovider也不行，有什么办法嘛，谢谢您

**Comment by xxxzc** [comment]
最近天热了确实有不少人反映这个问题，但我没遇到= =，有人说是 vrm 或者 ssd 过热导致的，目前还没有明确的说法。

**Comment by chenyaokaiccc** [comment]
> 最近天热了确实有不少人反映这个问题，但我没遇到= =，有人说是 vrm 或者 ssd 过热导致的，目前还没有明确的说法。
已经解决了，看网上说是因为电脑有静电，把电池拔掉，长按开机键把静电放光就可以了
