### ISSUE TITLE
请问大佬，在此配置文件下，可以将系统从10.15.5升级到10.15.6吗？

### ISSUE THREAD

**Issue by tiange1949** [xxxzc/xps15-9550-macos#63]
- 之前按照大佬给的OC配置文件以及大佬亲自的指导，成功给XPS 9550 安装上了10.15.5的黑苹果系统。

- 今日购入了Dell U2720QM外接显示器，实测hdmi2.0接口正常，能够顺利输出4k 60Hz。

- 最近，系统老是提示我更新到10.15.6，请问大佬在现有驱动和配置文件下，可以选择升级吗？

- 如果不能升级，有什么办法去除设置的小红点和禁用系统更新提示呢？

（谷歌百度了一圈，命令行什么的都没有生效，故求助大佬-^-）
![image](https://user-images.githubusercontent.com/26919925/88689161-be518080-d12c-11ea-93b3-7ccd67d104c2.png)
![image](https://user-images.githubusercontent.com/26919925/88689234-d32e1400-d12c-11ea-8903-6cd3067a5174.png)
![image](https://user-images.githubusercontent.com/26919925/88689282-e214c680-d12c-11ea-99b0-eea63918493c.png)

**Comment by xxxzc** [comment]
可以的
