### ISSUE TITLE
python3 update.py --gen

### ISSUE THREAD

**Issue by ghost** [xxxzc/xps15-9550-macos#65]
The generated gen_smbios.plist data caused OC not to boot. I had to revert back to the original config.plist

**Comment by xxxzc** [comment]
Please post the error log and attach your config.plist after running this script. 
`--gen` only replace the values of MLB, SystemSerialNumber and SystemUUID that should not affect boot up.
https://github.com/xxxzc/xps15-9550-macos/blob/32e7d2b4a5f9fcd420d236fcfc14c634d3207fad/OC/config.plist#L585-L592
