### ISSUE TITLE
opencore modify graphics memory

### ISSUE THREAD

**Issue by jf7686** [xxxzc/xps15-9550-macos#66]
How to modify graphics memory to 1536?

**Comment by xxxzc** [comment]
Graphics memeory is 1536 by default.
https://github.com/xxxzc/xps15-9550-macos/blob/32e7d2b4a5f9fcd420d236fcfc14c634d3207fad/CLOVER/config.plist#L186-L189

**Comment by jf7686** [comment]
OK, thank you.
