### ISSUE TITLE
DELL PRECISION 5510 BLACK SCREEN AFTER SLEEP

### ISSUE THREAD

**Issue by imanng** [xxxzc/xps15-9550-macos#67]
Hi,
I am using dell precision 5510 - I7 6820HQ, 16GB, 512GB, 4K screen. I tried to install macOS 10.15.6 with your EFI last OC version. Almost everything working.
But I can't wake up from sleep. It has been black screen while the keyboard and power button are still active.

I tried to research some solutions but it failed. 😓

- Image:
![20200830_081637 jpg 565a4b9194b23c81e9a116500eb484ec](https://user-images.githubusercontent.com/39839527/92061506-ab336f80-edc0-11ea-88f9-33148d110eb3.jpg)

- My EFI:
https://drive.google.com/file/d/19iwdpLM_CyniJsonYlRuXH_x7B3R4Opi/view?usp=sharing

**Comment by xxxzc** [comment]
Please make sure you have followed [sleep-wake](https://github.com/xxxzc/xps15-9550-macos#sleep-wake) section in my README(run commands and uncheck all options in Energy Saver).

When you encounter this issue next time, please force reboot and run `log show --last 2h > ~/Desktop/log_5510.txt`, and attach this log file.

**Comment by imanng** [comment]
I have followed sleep-wake section in your guide. This is info from pmset -g.
![image](https://user-images.githubusercontent.com/39839527/92298293-761a4f00-ef71-11ea-9d51-72b8dfef301a.png)
This is log file. My laptop has slept from 11:26 => 11:34.
https://drive.google.com/file/d/12F9EFxgvUsCNeasCiakjmq8wgZ8di3r8/view?usp=sharing

**Comment by xxxzc** [comment]
Sorry, I forgot another log, please attach `pmset -g log`.
The problem is "sleep wake failure in EFI", this is a very strange problem that I had faced before, but I don't know how to fix it.
Do you try clean nvram and use CLOVER or other 5510's configurations?
You can try to remove SSDT-DGPU, SSDT-PCI0 and SSDT-ZPTS in /EFI/ACPI folder, then run python3 update.py --acpi to update config file, these SSDTs may affect sleep wake.

**Comment by xxxzc** [comment]
You can try to remove SSDT-DGPU, SSDT-PCI0 and SSDT-ZPTS in /EFI/ACPI folder, then run `python3 update.py --acpi` to update config file. These SSDTs may affect sleep wake.

**Comment by imanng** [comment]
I tried some another EFI but it fails.
This is pm_set_log file.

[pmset_log_5510.txt](https://github.com/xxxzc/xps15-9550-macos/files/5178241/pmset_log_5510.txt)
-----------------
When I tried to create a new SSDT, I tested sleep mode with AC Power, it seems to work.
When I use the battery, it doesn't work.
Have you encountered this problem?

**Comment by xxxzc** [comment]
[RTCMemoryFixup](https://github.com/acidanthera/RTCMemoryFixup) may fix this problem

**Comment by imanng** [comment]
I will try it.
Thanks

**Comment by imanng** [comment]
I reset bios and it works perfectly with your EFI.
Thanks for supporting me. 😍

**Comment by khongtrunght** [comment]
> I reset bios and it works perfectly with your EFI.
> Thanks for supporting me. 😍

Is reset bios the same as reset nvram, can you help me ?

**Comment by imanng** [comment]
Hi, I reset bios to default config in the bios setting.
