### ISSUE TITLE
Unable to start installer: Error code: Err(0xE), 0 @ LocHB

### ISSUE THREAD

**Issue by bscubed** [xxxzc/xps15-9550-macos#69]
Apologies for my lack of knowledge, this is my first time trying to set up a Hackintosh.
I have been trying to install Mac OS Catalina 10.15.6 for about two days and nothing has been working.

I have a Dell XPS 15 9550 with the following specs:
CPU: Intel Core i7 6700HQ
GPU: Intel HD 530 / Nvidia GTX 960M
Display: FHD 1920x1080
NVMe SSD: Toshiba THNSN5256GPU7 256GB
SATA hard drive: Western Digital WD10JPVX-22JC3T0 1TB
WiFi/Bluetooth: Intel Wireless 8265 (used to be Killer Wireless)

After launching the Installer from the OpenCore bootloader, it fails after about 5 seconds with the following errors:
![photo_2020-10-27_14-22-08](https://user-images.githubusercontent.com/1623826/97349402-d1780780-1865-11eb-8168-417808931805.jpg)

I've tried Clover as well with multiple configurations, but it always fails with the same error.

I don't have access to a Mac installation, so I created the Install USB using [gibMacOS](https://github.com/corpnewt/gibMacOS) but I don't think that's the root of the issue since others have installed OpenCore fine with gibMacOS.

Any help would be greatly appreciated. Attached is my config.plist: [config.zip](https://github.com/xxxzc/xps15-9550-macos/files/5447538/config.zip)

Edit: Here's the full log: [opencore-2020-10-27-200143.txt](https://github.com/xxxzc/xps15-9550-macos/files/5447854/opencore-2020-10-27-200143.txt)

**Comment by bscubed** [comment]
I think the issue is actually this line:
```[EB|`LD:OFS] Err(0xE) @ OPEN (System\\Library\\PrelinkedKernels\\immutablekernel.development)```
As referenced in the [OpenCore troubleshooting guide](https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/kernel-issues.html#stuck-on-eb-ld-ofs-err-0xe-when-booting-preboot-volume).

Do you think that's the issue? And if so, how would I go about fixing that without access to a Mac Recovery?

**Comment by HelloAlone** [comment]
> I think the issue is actually this line:
> `` [EB|`LD:OFS] Err(0xE) @ OPEN (System\\Library\\PrelinkedKernels\\immutablekernel.development) ``
> As referenced in the [OpenCore troubleshooting guide](https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/kernel-issues.html#stuck-on-eb-ld-ofs-err-0xe-when-booting-preboot-volume).
> 
> Do you think that's the issue? And if so, how would I go about fixing that without access to a Mac Recovery?

Same problem. But I soon realized that it is because of a mismatched OpenCore version. This project requires version 0.6.0 of OpenCore, but gibMacOS automatically downloads the latest version!

**Comment by bscubed** [comment]
You're a genius, that fixed it. Thank you so much! Any idea what's causing 0.6.1+ not to boot?

**Comment by HelloAlone** [comment]
> You're a genius, that fixed it. Thank you so much! Any idea what's causing 0.6.1+ not to boot?

I haven't tried anything other than 0.6.2 and 0.6.0, so I don't know if 0.6.1 will work. OpenCore has broken compatibility many times, so I guess we should update all kexts to newest version as well. Honestly, I didn't see anything wrong with plist. Try adding more quirks (about CPU) ? But I don't want to waste my time, after all my hackintosh is working fine now. :)

**Comment by bscubed** [comment]
Very true. I'll close this issue for now and look into it on my own. Thanks!
