### ISSUE TITLE
Hello Author, I do not boot using this EFI with Big Sur

### ISSUE THREAD

**Issue by tiendatnguyen997** [xxxzc/xps15-9550-macos#75]
Hello author, I am using Dell 5510. I7 6820HQ, Ram 16Gb, SSD Samsung SM951 512Gb, Card wifi Intel 8620, 4k screen. T knew that my Dell 5510 was a ver of Dell XPS 9550. I used this EFI XPS15-9550-OC-INTEL-201116.zip with Open Core 0.6.3, My laptop is not work. While booting process, it has error in the screen shot ( the screen did not run afer this code). I am using Catalian, which is pefect. Please help me. Thank you so much.
![image](https://user-images.githubusercontent.com/74667446/99546493-0997e380-29e9-11eb-83b1-4944aa630f50.png)

**Comment by xxxzc** [comment]
This happend if you don't force your panel to run at 48Hz.

**Comment by tiendatnguyen997** [comment]
> This happend if you don't force your panel to run at 48Hz.

Thank you bro so much. I got it and it work pefect with my Dell 5510 ( 4k, intel 8260, I7 6820HQ, SSD SM951).
