### ISSUE TITLE
Sleep Wakup Faild - Dell 5510

### ISSUE THREAD

**Issue by irisvn** [xxxzc/xps15-9550-macos#77]
Hello, 
I have issue "Sleep Wakup Faild". Please check it ^^ Thank you. 

Info: 

Sleep Wake failure in EFI

Failure code:: 0xffffffff 0x0000001f

Please IGNORE the below stackshot

================================================================
Date/Time:        2020-11-23 11:59:36 +0700
OS Version:       ??? ??? (Build ???)
Architecture:     x86_64
Report Version:   29

Data Source:      Stackshots
Shared Cache:     0x83a1000 9D861197-B714-36FE-9EAC-E39F5CB89320

Event:            Sleep Wake Failure
Duration:         0.00s
Steps:            1

Boot args:        darkwake=1 

Time Awake Since Boot: 11s

Process:          swd [253]
Architecture:     x86_64
Footprint:        464 KB
Start time:       2020-11-23 11:59:36 +0700
End time:         2020-11-23 11:59:36 +0700
Num samples:      1 (1)

  Thread 0x721    1 sample (1)    priority 4 (base 4)
  <thread QoS background (requested background), thread darwinbg, process darwinbg, IO tier 2>
  1  start + 1 (libdyld.dylib + 109769) [0x7fff6f3c6cc9] 1
    1  ??? [0x101d9e454] 1
      1  ??? [0x101d9e1dd] 1
        1  __stack_snapshot_with_config + 10 (libsystem_kernel.dylib + 135862) [0x7fff6f5282b6] 1
         *1  ??? [0xffffff80002bf206] 1
           *1  ??? [0xffffff8000982437] 1
             *1  ??? [0xffffff800089afc1] 1
               *1  ??? [0xffffff80002e29e7] (running) 1

  Binary Images:
        0x7fff6f3ac000 -     0x7fff6f3e2fff  libdyld.dylib (750.6)                 <789A18C2-8AC7-3C88-813D-CD674376585D>  /usr/lib/system/libdyld.dylib
        0x7fff6f507000 -     0x7fff6f533fff  libsystem_kernel.dylib (6153.141.2.2) <5CDBBC06-6CA6-3432-9FDA-681047866F3E>  /usr/lib/system/libsystem_kernel.dylib
Model: MacBookPro13,3, BootROM 429.40.5.0.0, 4 processors, Quad-Core Intel Core i7, 2.7 GHz, 16 GB, SMC 2.38f11
Graphics: kHW_IntelHDGraphics530Item, Intel HD Graphics 530, spdisplays_builtin
Memory Module: DIMM A/DIMM A, 8 GB, DDR4, 2133 MHz, Micron, 16ATF1G64HZ-2G1B1
Memory Module: DIMM B/DIMM B, 8 GB, DDR4, 2133 MHz, Micron, 16ATF1G64HZ-2G1B1
Bluetooth: Version 7.0.6f7, 3 services, 17 devices, 1 incoming serial ports
Serial ATA Device: Samsung SSD 860 EVO M.2 500GB, 500.11 GB
USB Device: USB 3.0 Bus
USB Device: Integrated_Webcam_HD
USB Device: Bluetooth HCI
USB Device: USB Receiver
Thunderbolt Bus:

**Comment by xxxzc** [comment]
https://github.com/xxxzc/xps15-9550-macos/issues/67

**Comment by irisvn** [comment]
Thank you, it working 👍
