### ISSUE TITLE
最新版本的小问题

### ISSUE THREAD

**Issue by frankbird2b** [xxxzc/xps15-9550-macos#8]
1 开机dell标志要很久很久才进到clover界面 2 偶尔无原因会禁行标志无法进到系统，重启又能进去了。再次感谢楼主不断完善

**Comment by xxxzc** [comment]
第一个问题我也很苦恼，不知道是什么原因，之前查过可能是 apfs 的原因
第二个问题需要 -v 截图给我我才能（可能能）确定是什么问题

我用回 win10 了= =因为有时候长时间睡眠盒盖打开会花屏，最近没时间去解决

**Comment by frankbird2b** [comment]
> 第一个问题我也很苦恼，不知道是什么原因，之前查过可能是 apfs 的原因
> 第二个问题需要 -v 截图给我我才能（可能能）确定是什么问题
> 
> 我用回 win10 了= =因为有时候长时间睡眠盒盖打开会花屏，最近没时间去解决

我的电脑黑苹果比win10好用，win下经常找不到原因会卡死或者蓝屏，苹果相对而言香很多啊哈哈，可以正常使用没有问题了

**Comment by xyx208** [comment]
> 第一个问题我也很苦恼，不知道是什么原因，之前查过可能是 apfs 的原因
> 第二个问题需要 -v 截图给我我才能（可能能）确定是什么问题
> 
> 我用回 win10 了= =因为有时候长时间睡眠盒盖打开会花屏，最近没时间去解决

大佬 ，我用你的配置很完美 ，只有一个小问题:合盖后或者关屏后，就不能点亮屏幕，声音什么都正常，但是屏幕背光是有的。

**Comment by xxxzc** [comment]
> > 第一个问题我也很苦恼，不知道是什么原因，之前查过可能是 apfs 的原因
> > 第二个问题需要 -v 截图给我我才能（可能能）确定是什么问题
> > 我用回 win10 了= =因为有时候长时间睡眠盒盖打开会花屏，最近没时间去解决
> 
> 大佬 ，我用你的配置很完美 ，只有一个小问题:合盖后或者关屏后，就不能点亮屏幕，声音什么都正常，但是屏幕背光是有的。

emm...这个是以前遇到过的问题，现在就非常偶然得遇到过一次花屏。。
可以检查下下面这些：

0. 配置文件是最新的吗？
1. 点亮屏幕有没有多按几次回车？
2. 有没有执行下面这些命名？
```
sudo pmset -a hibernatemode 0
sudo pmset -a autopoweroff 0
sudo pmset -a disksleep 0
sudo pmset -a standby 0
```
3. 节能设置里有没有取消勾选所有选项？
4. Console.app - Mac 分析数据 和 系统报告里有没有什么关于睡眠的数据？

另外最好发下系统配置给我

**Comment by frankbird2b** [comment]
> > 第一个问题我也很苦恼，不知道是什么原因，之前查过可能是 apfs 的原因
> > 第二个问题需要 -v 截图给我我才能（可能能）确定是什么问题
> > 我用回 win10 了= =因为有时候长时间睡眠盒盖打开会花屏，最近没时间去解决
> 
> 大佬 ，我用你的配置很完美 ，只有一个小问题:合盖后或者关屏后，就不能点亮屏幕，声音什么都正常，但是屏幕背光是有的。

我用老版本的曾经也有这个问题，换最新的配置解决了

**Comment by xxxzc** [comment]
好吧。。重建下缓存就可以用了

**Comment by frankbird2b** [comment]
> 顺便说一下不要升到 10.14.1 。。。VoodooI2CHID不能加载。。。
> [alexandred/VoodooI2C#128](https://github.com/alexandred/VoodooI2C/issues/128)
> 
> 我翻车了= =

等大佬搞定了我再更新😀

**Comment by xyx208** [comment]
> > > 第一个问题我也很苦恼，不知道是什么原因，之前查过可能是 apfs 的原因
> > > 第二个问题需要 -v 截图给我我才能（可能能）确定是什么问题
> > > 我用回 win10 了= =因为有时候长时间睡眠盒盖打开会花屏，最近没时间去解决
> > 
> > 
> > 大佬 ，我用你的配置很完美 ，只有一个小问题:合盖后或者关屏后，就不能点亮屏幕，声音什么都正常，但是屏幕背光是有的。
> 
> 我用老版本的曾经也有这个问题，换最新的配置解决了

昨晚我看了下，果然是老版。。。。我换最新的也好了。

**Comment by upupming** [comment]
> 昨晚我看了下，果然是老版。。。。我换最新的也好了。

请问新版是如何修复的呢？我也遇到了类似的情况，发帖求助至今没有解决呢。https://www.tonymacx86.com/threads/black-screen-when-waking-from-sleep-on-mojave-10-14-3-lenovo-g50-80.271315/
