### ISSUE TITLE
XPS15-9550-OC-BRCM-201208 Causing KP on Catalina and Big Sur

### ISSUE THREAD

**Issue by azeezsker** [xxxzc/xps15-9550-macos#81]
XPS15-9550-OC-BRCM-201208 causing KP on Catalina and Big Sur both, seems to be related to Lilu kext
![IMG_20201210_003740](https://user-images.githubusercontent.com/74827240/101676888-cda0ed00-3a81-11eb-834b-70eed4ddfa94.jpg)

**Comment by xxxzc** [comment]
Try rebooting a few more times.

**Comment by xxxzc** [comment]
You can try https://github.com/xxxzc/xps15-9550-macos/issues/74#issuecomment-732144560

Add your fault CR2 code to https://github.com/xxxzc/xps15-9550-macos/blob/e3e96da9b5371215c20627c5e17336cc8c8358b2/OC/config.plist#L173

**Comment by azeezsker** [comment]
Thanks for XPS15-9550-OC-BRCM-201210, works after applying "AAPL00,override-no-connect" via update.py. Without it, the system boots but OS does not start, verbose stops at some random line. 

This repo however limits big sur display refresh rate to 48 Hz even for Catalina. Is there any fix to restore refresh rate for Catalina 60Hz for 4k displays?

Is there any progress on Big Sur 4k display at 60Hz development work?

**Comment by xxxzc** [comment]
The latest commit in WhateverGreen make display working in 60Hz. See my latest release.

**Comment by azeezsker** [comment]
Thanks for the update, XPS15-9550-OC-BRCM-201218 does not boot due to KP.
After including Booter>Mmiowhitelist system boots but OS does not start (blank screen).
Tried with boot args -cdfon, -igfxmpc but no success.

**Comment by xxxzc** [comment]
> system boots but OS does not start

what dose 'system boots' mean? Boot to OC, booting after Apple logo but blank screen?

**Comment by azeezsker** [comment]
Yes, boots to OC and then it stops. There is sound in background when i press volume key but no login screen.

**Comment by xxxzc** [comment]
Please upload your EFI.

**Comment by azeezsker** [comment]
Hi, I used repo released by WMCHRIS, and its working fine.

Thanks for your reply though.
