### ISSUE TITLE
安装后键盘和时间出现问题

### ISSUE THREAD

**Issue by yuki0320** [xxxzc/xps15-9550-macos#82]
型号 | XPS15-9550/MacBookPro13,3 | 版本 | 10.15.7 19H2
-- | -- | -- | --
处理器 | Intel Core i5-6300HQ | 核显 | HD Graphics 530
内存 | Micron 2133MHz DDR4 4GB x2 | 存储 | 铠侠 RC10（东芝RC500） 512GB
声卡 | Realtek ALC298 | 网卡 | Dell Wireless 1830
内屏 | Sharp LQ156D1 UHD | 显示器 | HKC GF40 FHD 144Hz
open core 版本 |  0.6.0 | EFI | 200807

安装后键盘的Alt和command键调换了，按照你的方法设置了睡眠后，合盖再打开时间会停留在合盖前的时间

**Comment by xxxzc** [comment]
alt command 可以在键盘设置右下的按钮里换

**Comment by yuki0320** [comment]
> alt command 可以在键盘设置右下的按钮里换

好的
