### ISSUE TITLE
[NOT ISSUES] FANS speed fixed at 2500 rpm

### ISSUE THREAD

**Issue by HungThinhIT** [xxxzc/xps15-9550-macos#83]
Hello @xxxzc, 
First of all, I really appreciate the effort you making this Hackintosh project. Thank you very much!
I'm using `XPS15-9550-OC-BRCM-201210.zip` config with `MacOS 10.15.7` on my `Dell Precision 5510 - 4K` very perfect.
But I realized that 2 fans are probably fixed at `2500 rpm`, when I try to test CPU, 2 fans still fixed at ~2500rpm and can't higher.
So can we optimize fan speed automatic higher like native or modify fan speed manually?
Thank you, hope you can reply me!

<img width="960" alt="Screen Shot 2020-12-16 at 10 00 07" src="https://user-images.githubusercontent.com/33023931/102299932-78377500-3f86-11eb-81e1-c94008eeaffa.png">

**Comment by xxxzc** [comment]
You can use fan control app(like Macs Fan Control or iStat Menus) in macOS thanks to the SMCDellSensors in VirtualSMC.

**Comment by HungThinhIT** [comment]
> You can use fan control app(like Macs Fan Control or iStat Menus) in macOS thanks to the SMCDellSensors in VirtualSMC.

@xxxzc Thanks for your response!
I used that apps (iStat Menu + Macs Fan Control) but it's not effect to any fans.
`SMCDellSensors` and `VirtualSMC` kexts already loaded in OC.
Can you take a look again in your Laptop.
Best Regard!

List non-apple kext loaded:
[kextstat.txt](https://github.com/xxxzc/xps15-9550-macos/files/5701583/kextstat.txt)


![Screen Shot 2020-12-16 at 16 08 39](https://user-images.githubusercontent.com/33023931/102328153-48559500-3fb9-11eb-89a7-ffbab701ac87.png)

**Comment by HungThinhIT** [comment]
My bad. When I try to installing `Xcode` fans speed changed.
System control fan working good, 2500 rpm because temperator cool.

And I forgot select profile on menu bar, so it's not effect
<img width="591" alt="Screen Shot 2020-12-16 at 18 16 35" src="https://user-images.githubusercontent.com/33023931/102341732-d71edd80-3fca-11eb-9d64-cf3fd07be6b9.png">
