### ISSUE TITLE
Stuck at apple logo

### ISSUE THREAD

**Issue by OscarWoHA** [xxxzc/xps15-9550-macos#84]
Hi, I'm trying to Hackintosh my DELL XPS 9550 with the OpenCore, but I find my self stuck at the apple logo with the machine not booting into the installer at all.

I am pretty new to hackintoshing, but not a OS hack yourself to the goal noob at all. Would love some help with troubleshooting though.

Specifications on the machine:
- DELL XPS 9550
- Intel Core i7-6700HQ
- 32 GB of RAM
- Samsung 970 EVO Plus 500GB M.2 SSD
- I'm using windows to create the installer, and my goal is to install Catalina for now.

**Comment by xxxzc** [comment]
press cmd+v in OpenCore GUI to enable verbose mode

**Comment by OscarWoHA** [comment]
I’m having the same issues as in #85, I’ll close this issue and we can continue debugging/discussion there.
