### ISSUE TITLE
大佬，使用了最新的EFI笔记本屏幕暂停，外接显示器可以显示，麻烦指导一下。

### ISSUE THREAD

**Issue by xyx208** [xxxzc/xps15-9550-macos#86]
![Uploading image.png…]()
感谢大佬的辛苦贡献！
![微信图片_20201221210501](https://user-images.githubusercontent.com/3462451/102780032-37998a80-43d0-11eb-98df-3269cbdafb1e.jpg)

**Comment by xyx208** [comment]
> 感谢大佬的辛苦贡献！

我的电脑：
xps 15 9550
4K 屏幕
32GB
sn750 1T硬盘

**Comment by xxxzc** [comment]
应该是网卡的问题，试试把 AirportBrcmFixup 先删了（别忘了config，可以直接 `python3 update.py --config`）或者 BIOS 里禁用网卡试试能不能启动

**Comment by xyx208** [comment]
> rcmFixup 先删了（别忘了config，可以直接 `python3 update.py --config`）或者 BIOS 里禁用网卡试试能不能启动

好的，我明天试试，谢谢！

**Comment by xuerake** [comment]
> 应该是网卡的问题，试试把 AirportBrcmFixup 先删了（别忘了config，可以直接 `python3 update.py --config`）或者 BIOS 里禁用网卡试试能不能启动

大佬，我的9550是 1080P的，试过propertree 里修改 UIScale 由2改成 AQ== 提示非法值，这里是不是应该和OC一样改成1啊
OC: NVRAM/Add/4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14/UIScale -> AQ==
CLOVER: BootGraphics/UIScale -> 1
Or simply run python3 update.py --display fhd.

代码编辑器 运行python3 update.py, 这个是在github 里的code 还是电脑上用visual studio code 之类的操作，见到代码就头大的小白
感谢

**Comment by xxxzc** [comment]
@xuerake  CLOVER改成1，OC改成AQ==，可以直接用 [Clover Configurator](https://mackie100projects.altervista.org/download-clover-configurator/) 或者[OpenCore Configurator](https://mackie100projects.altervista.org/occ-changelog-version-2-19-1-0/)。

**Comment by xuerake** [comment]
> @xuerake CLOVER改成1，OC改成AQ==，可以直接用 [Clover Configurator](https://mackie100projects.altervista.org/download-clover-configurator/) 或者[OpenCore Configurator](https://mackie100projects.altervista.org/occ-changelog-version-2-19-1-0/)。

好的，谢谢大佬
还有一个问题，洗白三码，双系统 准备用OC引导
RM里提到 UUID要用win系统盘的，用这个替代洗白三码里的suuid 
会有冲突吗

**Comment by xxxzc** [comment]
> > @xuerake CLOVER改成1，OC改成AQ==，可以直接用 [Clover Configurator](https://mackie100projects.altervista.org/download-clover-configurator/) 或者[OpenCore Configurator](https://mackie100projects.altervista.org/occ-changelog-version-2-19-1-0/)。
> 
> 好的，谢谢大佬
> 还有一个问题，洗白三码，双系统 准备用OC引导
> RM里提到 UUID要用win系统盘的，用这个替代洗白三码里的suuid
> 会有冲突吗

反正我遇到过不用 Win 的 UUID 启动 Win 会出现 Win 未激活，使用 Win 的 UUID 后就没出现这个问题了。

**Comment by xyx208** [comment]
再次尝试后也不行，后面换了这个ef后成功装上了 BIG Sur,感谢各位大佬。
https://github.com/wmchris/DellXPS15-9550-OSX
各位可以试试。感谢大佬。

**Comment by xxxzc** [comment]
>   再次尝试后也不行，后面换了这个ef后成功装上了 BIG Sur,感谢各位大佬。
> https://github.com/wmchris/DellXPS15-9550-OSX
> 各位可以试试。感谢大佬。

太奇怪了，我对比了下没发现啥区别
