### ISSUE TITLE
#87 使用201218 Clover 卡LOGO, OC: Failed to load configuration

### ISSUE THREAD

**Issue by xuerake** [xxxzc/xps15-9550-macos#87]
![151608737439_ pic](https://user-images.githubusercontent.com/76392650/103012693-f1326000-4576-11eb-99fd-75433d56b4e0.jpg)
![141608737438_ pic](https://user-images.githubusercontent.com/76392650/103012725-f98a9b00-4576-11eb-803b-df71302457af.jpg)
![111608737435_ pic](https://user-images.githubusercontent.com/76392650/103012759-03ac9980-4577-11eb-8cec-d71e42e14702.jpg)

配置 XPS9550 1080P
CPU:英特尔 Core i7-6700HQ
RAM:镁光 DDR4 2400MHz
硬盘：东芝 THNSN5512GVU7 SAMPLE
显卡：英特尔 HD Graphics 530
显示器：夏普 SHP1453
网卡 博通DW1830
目前使用系统 Mojave 14.1

尝试升级15.7，使用的黑果小兵制作的镜像，macOS Catalina 10.15.7(19H15) Installer for Clover 5126 and OC 0.6.3 and PE 32G

第一次，配置好
OC: NVRAM/Add/4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14/UIScale -> AQ==
CLOVER: BootGraphics/UIScale -> 1
和三码
clover 卡logo OC: Failed to load configuration

第二次，直接用下载的clover 和oc 症状相同

update:
201210 故障依旧
201208 故障依旧
200807 故障依旧
201116-2 clover还是卡Logo  OC能进入安装，但是磁盘抹除失败，EFI盘调到500M, 再次进入，识别不到硬盘
明天再尝试

**Comment by xuerake** [comment]
update:201116-2
修改OC config
OC: NVRAM/Add/4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14/UIScale -> 01  每改成AQ==
用win 的UUID 和生成的三码
目前可以已经刷好 Catalina 15.7 9H2 
目前问题  声音有爆音
bug
使用safari 声音有爆音
蓝牙bug, 蓝牙两种模式，视频，音乐等时，会调用stereo
但是一旦视频通话，就会调用 handsfree, 然后就会有很大的杂音
暂时解决办法，声音设置里，把输入改成电脑内置
问题：视频通话和音频播放，只能存在一个？

双系统问题
把OC EFI拷贝到ESP启动盘，然后默认会在OC里启动win10,出现引导错误
进PE修复，又会出现OC无法引导的总是，都在抢Boot.efi
现在暂时是U盘引导，然后ESP引导win10, PD可以正常用bootcamp 使用双系统
有知道的大佬麻烦 告知下双系统完美启动的方法

**Comment by xuerake** [comment]
双系统引导的问题
尝试过以下路线
1 将ESP区，EFI文件夹清空，移入OC引导文件夹，引导win10失败
   修复win10引导，OC失败
2 参考https://imacos.top/2020/04/06/1559/
   用easyUEFI 加入OC选项，使用\EFI\OC\opencore.EFI
   并放在首位，引导win10失败
3 参考https://imacos.top/2020/04/06/1559/
   用easyUEFI 加入OC选项，使用\EFI\OC\opencore.EFI
   将win10放在首位，OC 使用F12 手动引导
   进入系统后，使用parallels desktop ,bootcamp 引导win10 又变成OC引导，失败
目前解决办法
win10 boot camp 放首位
OC放U盘引导，反正一般不断电就不重启

4 最终解决办法
win10 boot camp 放首位
系统默认进入win10
修改config文件，boot\ 移除microsoft 选项，使得parallels desktop 用boot camp 启动时，不调用OC而是直接调用win10的
后续再把OC调到首位看行不行
目前，开机可以手动选择进入 win10 或是 Mac parallels desktop 也可以用boot camp 启动

**Comment by xxxzc** [comment]
我是直接 BIOS 加 OpenCore.efi 作为引导，因为最近用 windows 比较多，所以 OC 改成 F12 启动了，当然 OC 直接启动也没问题，引导 Win 和 macOS 都没问题，不过需要注意的是用 OC 启动 Win 时，戴尔官网下载的驱动是无法安装的（现有的不受影响）。
我没用 parallels desktop 所以不知道会造成什么影响。

**Comment by xuerake** [comment]
> 我是直接 BIOS 加 OpenCore.efi 作为引导，因为最近用 windows 比较多，所以 OC 改成 F12 启动了，当然 OC 直接启动也没问题，引导 Win 和 macOS 都没问题，不过需要注意的是用 OC 启动 Win 时，戴尔官网下载的驱动是无法安装的（现有的不受影响）。
> 我没用 parallels desktop 所以不知道会造成什么影响。

感谢回复
目前我是OC BIOS 加OpenCore.efi 作为引导，放第一位，默认进入
win使用microsoft 目录下的引导，放第二位，
用OC引导，尝试了几次，都是引导失败，就放弃了
目前这样问题不大了，win10用的不多，Parallesls desktop, 够用了
