### ISSUE TITLE
连外接显示器无反应，从14.1升到15.7，以前HDMI是可以用 201116-2 版本的OC引导

### ISSUE THREAD

**Issue by xuerake** [xxxzc/xps15-9550-macos#88]
![WX20201225-201919](https://user-images.githubusercontent.com/76392650/103134768-8dcb3e00-46ee-11eb-99af-45538ff1fcdb.png)
连外接显示器无反应，从14.1升到15.7，以前HDMI是可以用 201116-2 版本的OC引导
搜了一圈google， 没发现相同的，
看了下，核显是驱动好的
Intel HD Graphics 530:

  Chipset Model:	Intel HD Graphics 530
  Type:	GPU
  Bus:	Built-In
  VRAM (Dynamic, Max):	2048 MB
  Vendor:	Intel
  Device ID:	0x191b
  Revision ID:	0x0006
  Metal:	Supported, feature set macOS GPUFamily2 v1
  Displays:
Display:
  Resolution:	1920 x 1080 (1080p FHD - Full High Definition)
  UI Looks like:	1920 x 1080
  Framebuffer Depth:	24-Bit Color (ARGB8888)
  Main Display:	Yes
  Mirror:	Off
  Online:	Yes
  Automatically Adjust Brightness:	No
  Connection Type:	Internal

**Comment by xuerake** [comment]
看了另一个大佬的解决方案
https://github.com/corenel/XPS9550-macOS
To make external monitor works (if you use iMac17,1 SMBIOS), you should do following steps:

1 Open /System/Library/Extensions/AppleGraphicsControl.kext/Contents/PlugIns/AppleGraphicsDevicePolicy.kext/Contents/Info.plist.

2 Find the Borad-ID which used in your config.plist such as "Mac-B809C3757DA9BB8D" or "Mac-65CE76090165799A" or "Mac-DB15BD556843C820".

3 Replace the attribute Config2 with none

4 Execute commands sudo kextcache -system-prelinked-kernel and sudo kextcache -system-caches.

5 Reboot and everything is done.

**Comment by xuerake** [comment]
参考201208 config配置
在DeviceProperties-设备属性设置
PciRoot(0x0)Pci(0x2,0x0)
填入 agdpmod   vit9696    字符类型
开启允许HDMI线搞定了
![WX20201226-130137](https://user-images.githubusercontent.com/76392650/103145758-82255900-477a-11eb-8a70-7edf0be43184.png)

**Comment by xuerake** [comment]
目前就是声卡还有点问题
1 耳机孔，音质差，特别是人声特别低，播放视频时，BGM声音正常，但同时人声很低，切换回蓝牙又没有问题
2 就是视频通话和播放视频时，音质的问题，会自动切换到handsfree. 而不是stereo
继续研究下怎么解决

**Comment by xxxzc** [comment]
音频可以参考下这个 https://github.com/jardenliu/XPS15-9560-BigSur/tree/OpenCore/Post-install/ALCPlugFix-Swift
