### ISSUE TITLE
iMessage激活问题

### ISSUE THREAD

**Issue by Marc18x** [xxxzc/xps15-9550-macos#9]
想问一下要怎么修改clover里的三码配置才能正常激活iMessage服务呀？
按照网上的教程只能登陆iCloud，安装了好几次系统都没办法正常激活iMessage。

**Comment by xxxzc** [comment]
我只有使用 app store 额。目前尝试过哪些方法？

**Comment by carking** [comment]
自己Google  idiot guide iMessage

**Comment by Marc18x** [comment]
> 我只有使用 app store 额。目前尝试过哪些方法？

http://www.ituring.com.cn/article/274156
之前10.13的时候用这个方法能正常激活iMessage
但是这次装10.14试了好几次发现都激活不了了
